################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       01-Parameters.R                                #####
##### Use this file to tune the outputs of the code by selecting which     #####
##### features to run and on which type of data                            #####
################################################################################

# Names of the main directories in the project
DataDir = "Data/"
tournamentDataDir = paste0(DataDir,"Tournament/")
ResultDir = "Results/"

# Format of the wanted events
# # Leave this vector untouched if used, to avoid typing mistakes
MtgFormats = c("1" = "Sealed",
               "2" = "Standard",
               "3" = "Pioneer",
               "4" = "Modern",
               "5" = "Pauper",
               "6" = "Legacy",
               "7" = "Vintage",
               "8" = "All Formats")
MtgFormat = MtgFormats[7]

# MtgFormat = "Modern"

# Name of the tournament result data source file for the corresponding format
# Currently automatically updated based on the format name
TournamentResultFile = paste0(tournamentDataDir,MtgFormat,"_data.json")

#Earliest date - if NA, starts from the beginning of the data
Beginning = "2023-03-13"

#Latest date - if NA, goes up to the end of the data
End = "2023-04-10"

# Event type:
# All sources = Everything (except MTGO Leagues - for any filter)
# All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
# Full Meta Events = Only events with the full metagame available 
# (not MTGO Official results)
# ManaTraders = ManaTraders Series results
# Paper Events Full Meta = Full esults from MTG Melee
# Paper Events Top32 = Results of the top32 from MTG Melee
# MTGO Official Competitions = Results from the MTGO website
# MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
# MTGO Preliminaries = As per name

# Leave this vector untouched if used, to avoid typing mistakes
EventTypes = c("1" = "All sources",
               "2" = "All Events Top32",
               "3" = "Full Meta Events",
               "4" = "ManaTraders", 
               "5" = "Paper Events (Full Meta)",
               "6" = "Paper Events (Top32)",
               "7" = "MTGO Official Competitions", 
               "8" = "MTGO Events Top32",
               "9" = "MTGO Preliminaries")

EventType = EventTypes[8]

#Required metagame share to appear on charts (gets converted to % later)
ChartShare = 2
# Cut for the metagame analysis
StatShare = ChartShare
# Automatically update this Share values above with the average presence if TRUE
# The minimum value for ChartShare is 1 (otherwise too small for graphs) 
Share.autoupdate = T

# The definition of metagame presence (aka share) to use. 
# It can be:
# - "Copies": the number of lines in the dataframe dedicated to that archetype
# - "Players": the number of different players piloting that archetype
# - "Matches": the number of matches played by the archetype
Presence = "Matches"

# The value used for sorting the data in the win rate graph.
# It can be either "MeasuredWinrate" or "CI95LowerBound" (the lower bound of
# the 95% confidence interval on the win rate).
SortValue = "CI95LowerBound"

# Draw the presence axis with a logarithmic scale if TRUE, linear if FALSE
PresenceAxisLogScale = T

# The definition of metagame presence (aka share) to use, specifically to set
# the metric used to determine the size of the circles in 
# full_winrate_and_presence_graph(). 
# It can be:
# - "Copies": the number of lines in the dataframe dedicated to that archetype
# - "Players": the number of different players piloting that archetype
# - "Matches": the number of matches played by the archetype
Diameters = "Players"

CsvResultDir = "CSV files/"
ArchetypeCardDataResultDir = paste0(CsvResultDir, "Archetype Card Data/")
PlayerDataResultDir = paste0(CsvResultDir, "Player Data/")
PictureResultDir = "Picture files/"
TextResultDir = "Text files/"

addColor = F
