################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       01-Parameters.R                                #####
##### Use this file to tune the outputs of the code by selecting which     #####
##### features to run and on which type of data                            #####
################################################################################

# Names of the main directories in the project
DataDir = "Data/"
tournamentDataDir = paste0(DataDir,"Tournament/")
cardDataDir = paste0(DataDir,"Card/")
playerDataDir = paste0(DataDir,"Player/")
ResultDir = "Results/"

# Format of the wanted events
# # Leave this vector untouched if used, to avoid typing mistakes
MtgFormats = c("1" = "Limited",
               "2" = "Standard",
               "3" = "Pioneer",
               "4" = "Modern",
               "5" = "Pauper",
               "6" = "Duel-Commander",
               "7" = "Legacy",
               "8" = "Vintage",
               "9" = "All_Formats")
MtgFormat = MtgFormats[6]

# MtgFormat = "Vintage"

# Name of the tournament result data source file for the corresponding format
# Currently automatically updated based on the format name
TournamentResultFile = paste0(tournamentDataDir,MtgFormat,"_data.json")
# Name of the MTG JSON card data source file for the corresponding format
# Currently automatically updated based on the format name
mtgJsonFile = paste0(cardDataDir,MtgFormat,"Atomic.json")

#Earliest date - if NA, starts from the beginning of the data
Beginning = "2024-09-20"

#Latest date - if NA, goes up to the end of the data
End = "2024-09-23"

# Event type:
# All sources = Everything (except from MTGO Leagues and Team events - for any filter)
# All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
# Full Meta Events = Only events with the full metagame available 
# (not MTGO Official results)
# ManaTraders = ManaTraders Series results
# Paper Events Full Meta = Full results from MTG Melee
# Paper Events Top32 = Results of the top32 from MTG Melee
# MTGO Official Competitions = Results from the MTGO website
# MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
# MTGO Preliminaries = As per name

# Leave this vector untouched if used, to avoid typing mistakes
EventTypes = c("1" = "All events",
               "2" = "All events Top32",
               "3" = "All events Top8",
               "4" = "All events Top1",
               "5" = "All events X-2 or better",
               "6" = "All events X-1 or better",
               "7" = "Events with MU Data",
               "8" = "ManaTraders", 
               "9" = "Paper Events",
               "10" = "Paper Events Top32",
               "11" = "Paper Events Top8",
               "12" = "Paper Events Top1",
               "13" = "Paper Events X-2 or better",
               "14" = "Paper Events X-1 or better",
               "15" = "MTGO Events", 
               "16" = "MTGO Challenges and Qualifiers", 
               "17" = "MTGO Events Top8", 
               "18" = "MTGO Events Top1",
               "19" = "MTGO Events X-2 or better",
               "20" = "MTGO Events X-1 or better",
               "21" = "MTGO Preliminaries")

EventType = EventTypes[2]

#Required metagame share to appear on charts (gets converted to % later)
ChartShare = 2
# Cut for the metagame analysis
StatShare = ChartShare
# Automatically update this Share values above with the average presence if TRUE
# The minimum value for ChartShare is 1 (otherwise too small for graphs) 
Share.autoupdate = T

# The definition of metagame presence (aka share) to use. 
# It can be:
# - "Copies": the number of lines in the dataframe dedicated to that archetype
# - "Players": the number of different players piloting that archetype
# - "Matches": the number of matches played by the archetype
Presence = "Matches"

# The value used for sorting the data in the win rate graph.
# It can be either "Measured.Win.Rate" or "Lower.Bound.of.CI.on.WR" (the lower bound of
# the confidence interval on the win rate).
SortValue = "Lower.Bound.of.CI.on.WR"

#The percentage used for the confidence interval. By default it can be 0.95
CIPercent = 0.95

# Draw the presence axis with a logarithmic scale if TRUE, linear if FALSE
PresenceAxisLogScale = T

# The definition of metagame presence (aka share) to use, specifically to set
# the metric used to determine the size of the circles in 
# full_winrate_and_presence_graph(). 
# It can be:
# - "Copies": the number of lines in the dataframe dedicated to that archetype
# - "Players": the number of different players piloting that archetype
# - "Matches": the number of matches played by the archetype
Diameters = "Players"

CsvResultDir = "Table files/"
ArchetypeCardDataResultDir = paste0(CsvResultDir, "Archetype Card Data/")
ArchetypeWeeklyShareResultDir = paste0(CsvResultDir, "Archetype Weekly Share/")
PlayerDataResultDir = paste0(CsvResultDir, "Player Data/")
CardDataResultDir = paste0(CsvResultDir, "Card Data/")
PeriodComparisonDir = paste0(CsvResultDir, "Period Comparison files/")
PictureResultDir = "Picture files/"
TextResultDir = "Text files/"
AverageDeckListResultDir = paste0(TextResultDir, "Average Deck Lists/")
OptimizedDeckListResultDir = paste0(TextResultDir, "Optimized Deck Lists/")
BestDeckResultDir = paste0(TextResultDir, "Best Deck URL/")
AllDeckURLResultDir = paste0(TextResultDir, "All Deck URL/")
writeCSV = F
writeXLSX = T
writeJSON = F
includeMU = F

# TRUE when you want to manually add colors to some archetype names
# Still incomplete for easy use
addColor = F

# TRUE when you want to add a weight depending on the elapsed weeks
# Avoid using it if you want to look at the confidence intervals
timeWeight = F

MTGO_URL = "https://www.mtgo.com/"
Manatraders_URL = "https://www.manatraders.com/webshop/personal/"
MTGMelee_URL = "https://melee.gg/Decklist/View/"
