################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                      02-Metagame_Data_Treatment.R                    #####
##### Use this file to import functions that will provide the classical    #####
##### metagame analysis metrics.                                           #####
################################################################################

# # For development
# df = tournamentDf
# pieShare = PieShare
# presence = "Matches"
# beginning = Beginning
# end = End
# eventType = EventType
# mtgFormat = MTGFormat

library(dplyr) 
library(tidyverse)

graph_share = PieShare

#' List of all the different archetypes in the data
#'
#' @param df the dataframe generated by generate_df()
#'
#' @return a 1-column dataframe with the list of archetypes in the dataset
#' @export
#'
#' @examples
generate_archetype_list = function(df){
  archetype_list=data.frame(unique(df$Archetype$Archetype))
  names(archetype_list)[1] = c("Archetype")
  return(archetype_list)
}

#' Get the presence of a given archetype
#'
#' @param df the dataframe generated by generate_df() 
#' @param archetypeName a string, the name of the archetype you are looking for
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#'
#' @return an integer, the value of the presence by the chosen metric
#' @export
#'
#' @examples
get_archetype_presence = function(df,archetypeName,presence){
  df2=df[df$Archetype$Archetype==archetypeName,]
  
  return(ifelse(presence=="Copies",nrow(df2),
                                 ifelse(presence=="Players",
                                        length(unique(df2$Player)),
                                        ifelse(presence=="Matches",
                                               sum(df2$NRounds,df2$T8Matches),
                                               NA))))
}

#' Get the metagame presence (aka share) of each archetype
#'
#' @param df the dataframe generated by 
#' generate_df(EventType, MTGFormat, RawFile, Date.autoupdate) 
#' @param graph_share the % of presence under which archetypes are regrouped in
#' an "Other" category
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#'
#' @return
#' @export
#'
#' @examples
generate_metagame_data = function(df,graph_share,presence){
  
  archetype_list=generate_archetype_list(df)
  
  #Add the presence of each archetype in the data
  archetype_list$Presence = 
    sapply(X = archetype_list$Archetype, 
           FUN = get_archetype_presence, 
           df = df, presence = presence)
  
  # Aggregate all the archetypes accounting for less than graph_share % of the 
  # presence in the dataset
  graph_treshold = graph_share/100*sum(archetype_list$Presence)
  main_archetype_list = arrange(archetype_list[
    archetype_list$Presence >= graph_treshold, ],desc(Presence))
  
  # Add an "Other" category aggregating the presence of archetypes under 
  # graph_share %
  presence_other = sum(archetype_list[archetype_list$Presence < 
                                        graph_treshold, ]$Presence)
  if(presence_other>0){
    otherName = paste("Other (each <",graph_share,"%)",sep="")
    main_archetype_list = rbind(main_archetype_list, 
                                data.frame(Archetype = otherName, 
                                           Presence = presence_other))
  }
  
  # Add the metagame share as % in the dataframe
  main_archetype_list$Share = 
    as.numeric(format(round(
      main_archetype_list$Presence/sum(main_archetype_list$Presence)*100,
                                              1), nsmall = 1))
  
  # Force an order for the archetypes, with Other as the last one
  # (useful for ggplot)
  main_archetype_list$Archetype = reorder(main_archetype_list$Archetype, 
                                    as.numeric(main_archetype_list$Presence))
  if(presence_other>0){
    main_archetype_list$Archetype = 
      relevel(main_archetype_list$Archetype, otherName)
  }
  main_archetype_list$Archetype=fct_rev(main_archetype_list$Archetype)
  
  return(main_archetype_list)
}



