################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                      02-Metagame_Data_Treatment.R                    #####
##### Use this file to import functions that will provide the classical    #####
##### metagame analysis metrics.                                           #####
################################################################################

library(dplyr) 
library(tidyverse)

# # For development
# df = tournamentDf
# chartShare = ChartShare
# presence = "Matches"
# beginning = Beginning
# end = End
# eventType = EventType
# mtgFormat = MTGFormat

chartShare = ChartShare

#' List of all the different archetypes in the data
#'
#' @param df the dataframe generated by generate_df()
#'
#' @return a 1-column dataframe with the list of archetypes in the dataset
#' @export
#'
#' @examples
generate_archetype_list = function(df){
  archetype_list=data.frame(unique(df$Archetype$Archetype))
  names(archetype_list)[1] = c("Archetype")
  return(archetype_list)
}

#' Get the presence of a given archetype
#'
#' @param df the dataframe generated by generate_df() 
#' @param archetypeName a string, the name of the archetype you are looking for
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#'
#' @return an integer, the value of the presence by the chosen metric
#' @export
#'
#' @examples
get_archetype_presence = function(df,archetypeName,presence){
  df2=df[df$Archetype$Archetype==archetypeName,]
  
  return(ifelse(presence=="Copies",nrow(df2),
                                 ifelse(presence=="Players",
                                        length(unique(df2$Player)),
                                        ifelse(presence=="Matches",
                                               sum(df2$NRounds,df2$T8Matches),
                                               NA))))
}

#' Get the metagame presence (aka share) of each archetype
#'
#' @param df the dataframe generated by generate_df() 
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#'
#' @return
#' @export
#'
#' @examples
generate_metagame_data = function(df,chartShare,presence){
  
  archetype_list=generate_archetype_list(df)
  
  #Add the presence of each archetype in the data
  archetype_list$Presence = 
    sapply(X = archetype_list$Archetype, 
           FUN = get_archetype_presence, 
           df = df, presence = presence)
  
  # Aggregate all the archetypes accounting for less than chartShare % of the 
  # presence in the dataset
  graph_treshold = chartShare/100*sum(archetype_list$Presence)
  main_archetype_list = arrange(archetype_list[
    archetype_list$Presence >= graph_treshold, ],desc(Presence))
  
  # Add an "Other" category aggregating the presence of archetypes under 
  # chartShare %
  presence_other = sum(archetype_list[archetype_list$Presence < 
                                        graph_treshold, ]$Presence)
  if(presence_other>0){
    otherName = paste("Other (each <",chartShare,"%)",sep="")
    main_archetype_list = rbind(main_archetype_list, 
                                data.frame(Archetype = otherName, 
                                           Presence = presence_other))
  }
  
  # Add the metagame share as % in the dataframe
  main_archetype_list$Share = 
    as.numeric(format(round(
      main_archetype_list$Presence/sum(main_archetype_list$Presence)*100,
                                              1), nsmall = 1))
  
  # Force an order for the archetypes, with Other as the last one
  # (useful for ggplot)
  main_archetype_list$Archetype = reorder(main_archetype_list$Archetype, 
                                    as.numeric(main_archetype_list$Presence))
  if(presence_other>0){
    main_archetype_list$Archetype = 
      relevel(main_archetype_list$Archetype, otherName)
  }
  main_archetype_list$Archetype=fct_rev(main_archetype_list$Archetype)
  
  return(main_archetype_list)
}

#' Table of the presence and win rate by archetype
#'
#' @param df the dataframe generated by generate_df()  
#'
#' @return a dataframe with 9 colums and one row by archetype.
#' 1 column for the archetypes.
#' 3 columns for the presence (number of copies, number of players, number of
#' matches).
#' 3 columns for the win rate (the measured one and the lower and upper bounds
#' of the 95% confidence interval of the win rate).
#' @export
#'
#' @examples
archetype_metrics = function(df){
  #GET THE LIST OF THE DIFFERENT ARCHETYPES IN THE DATA
  metric_df=generate_archetype_list(df)
  
  metric_df$Copies=rep(0,nrow(metric_df))
  metric_df$Players=rep(0,nrow(metric_df))
  metric_df$Matches=rep(0,nrow(metric_df))
  metric_df$MeasuredWinrate=rep(0,nrow(metric_df))
  metric_df$CI95LowerBound=rep(0,nrow(metric_df))
  metric_df$CI95UpperBound=rep(0,nrow(metric_df))
  
  # Iterate over each archetype (1 row by archetype in metric_df)
  for (i in 1:nrow(metric_df)){
    # Filter only the data of the current archetype
    dfArchetypeI = df[df$Archetype$Archetype==metric_df$Archetype[i],]
    # Number of appearances in the data of the corresponding archetype
    metric_df$Copies[i] = nrow(dfArchetypeI)
    # Number of different players playing that deck
    metric_df$Players[i] = length(unique(dfArchetypeI$Player))
    # Number of matches played by that archetype in the data
    metric_df$Matches[i] = 
      sum(dfArchetypeI$NRounds, dfArchetypeI$T8Matches)
    
    # Number of wins of that archetype
    total_wins_arch = sum(dfArchetypeI$NWins + dfArchetypeI$T8Points/3)
    # Number of matches of that archetype - not accounting for draws
    total_matches_arch = sum(dfArchetypeI$NRounds - dfArchetypeI$NDraws + dfArchetypeI$T8Matches)
    
    # Measured winrate in the data
    metric_df$MeasuredWinrate[i] = binom.test(total_wins_arch, total_matches_arch, 
                                           p=0.5,alternative="two.sided", 
                                           conf.level=0.95)$estimate * 100
    # Lower bound of the 95% confidence intervals of the winrate          
    metric_df$CI95LowerBound[i] = binom.test(total_wins_arch, total_matches_arch, 
                                         p=0.5,alternative="two.sided", 
                                         conf.level=0.95)$conf.int[1] * 100
    # Upper bound of the 95% confidence intervals of the winrate  
    metric_df$CI95UpperBound[i] = binom.test(total_wins_arch, total_matches_arch, 
                                         p=0.5,alternative="two.sided", 
                                         conf.level=0.95)$conf.int[2] * 100
  }
  
  return(metric_df)
}

#' Normalized sum of presence and win rate
#'
#' @param metric_df the dataframe generated by archetype_metrics()  
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#'
#' @return a dataframe adding four columns to the input: 
#'  - the normalized input presence 
#'  - the normalized win rate 
#'  - the sum of the normalized presence and win rate
#'  - the rank based on that sum.
#' @export
#'
#' @examples
archetype_ranking = function(archetypeMetricsDf,presence){
  
  # Make the values of both metrics start at 0 by subtracting the minimum value
  metric_df_start_at_0 = archetypeMetricsDf
  
  # Use the logarithm of the presence
  # It usually has an exponential distribution, make it linear
  metric_df_start_at_0$NormalizedPresence = 
    unlist(log(metric_df_start_at_0[presence]) - 
    log(min(metric_df_start_at_0[presence])))
  
  metric_df_start_at_0$NormalizedMeasuredWinrate = 
    metric_df_start_at_0$MeasuredWinrate -
    min(metric_df_start_at_0$MeasuredWinrate)
  
  # Make the values of both metrics go up to 1 by dividing by the maximum value
  metric_df_between_0_and_1 = metric_df_start_at_0
  
  metric_df_between_0_and_1$NormalizedPresence = 
    metric_df_between_0_and_1$NormalizedPresence / 
    max(metric_df_between_0_and_1$NormalizedPresence)
  
  metric_df_between_0_and_1$NormalizedMeasuredWinrate = 
    metric_df_between_0_and_1$NormalizedMeasuredWinrate / 
    max(metric_df_between_0_and_1$NormalizedMeasuredWinrate)
  
  # We now have normalized metrics we can sum
  metric_df_normalized=metric_df_between_0_and_1
  metric_df_normalized$NormalizedSum = 
    metric_df_normalized$NormalizedPresence + 
    metric_df_normalized$NormalizedMeasuredWinrate
  
  # Order the rows based on the decreasing ranking according to that 
  # normalized sum
  metric_df_normalized = 
    metric_df_normalized[order(
      metric_df_normalized$NormalizedSum,decreasing=TRUE),]
  
  metric_df_normalized$Rank=(1:nrow(metric_df_normalized))
  
  return(metric_df_normalized)
}

#' Tier list data
#'
#' @param archetypeRankingDf the dataframe generated by archetype_ranking()
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#'
#' @return an updated dataframe keeping only the most present decks and adding a
#' tiers column.
#' @export
#'
#' @examples
archetype_tiers = function(archetypeRankingDf, presence, chartShare){
  
  # Add a presence column and scale it with the win rate up to 100 
  archetypeRankingDf$Presence = 100 * unlist(archetypeRankingDf[presence]) / 
    sum(unlist(archetypeRankingDf[presence]))
  archetypeRankingDf$MeasuredWinrate = archetypeRankingDf$MeasuredWinrate
  
  # Keep only the most present archetypes 
  presence_min = chartShare / 100 * sum(archetypeRankingDf[presence])
  tier_archetypes = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  meanMetric = mean(tier_archetypes$NormalizedSum)
  sdMetric = sd(tier_archetypes$NormalizedSum)
  
  tier_archetypes = tier_archetypes %>% 
    mutate(Tiers = case_when(
      NormalizedSum >= meanMetric + 3 * sdMetric ~ "0",
      NormalizedSum >= meanMetric + 2 * sdMetric ~ "0.5",
      NormalizedSum >= meanMetric + 1 * sdMetric ~ "1",
      NormalizedSum >= meanMetric ~ "1.5",
      NormalizedSum >= meanMetric - 1 * sdMetric ~ "2",
      NormalizedSum >= meanMetric - 2 * sdMetric ~ "2.5",
      NormalizedSum >= meanMetric - 3 * sdMetric ~ "3",
      TRUE ~ "Other"
    )
    )
}
