################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                        02-Simple_Getters.R                           #####
##### Use this file to run simple getters on the imported data.            #####
################################################################################

# install.packages("readr")
# install.packages("devtools")
# install.packages("data.table")
library("readr")
library("devtools")
library("data.table")

#' Get conflicted archetype URL
#'
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of URL of archetypes with Conflicts
#' @export
#'
#' @examples
getConflictURL = function(df){
  return(df[startsWith(df$Archetype$Archetype,"Conflict")==TRUE,]$AnchorUri)
}

#' Get conflicted archetype names
#'
#' @param df the dataframe returned bygenerate_df()
#'
#' @return the list of names of archetypes with Conflicts
#' @export
#'
#' @examples
getConflictArchetype = function(df){
  return(df[startsWith(df$Archetype$Archetype,
                       "Conflict")==TRUE,]$Archetype$Archetype)
}

#' Get Unknown archetype URL
#'
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of URL of archetypes classified as Unknown
#' @export
#'
#' @examples
getUnknown = function(df){
  return(df[df$Archetype$Archetype=="Unknown",]$AnchorUri)
}

#' Get all URL of decks with a given card
#'
#' @param cardName a string with the name of the card to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of decks with a specific card in the data. 
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getURLofCard = function(cardName,df){
  archetypeURL = c()
  for (i in 1:nrow(df)){
    if (length(grep(cardName,df$Mainboard[[i]]$CardName)) + 
        length(grep(cardName,df$Sideboard[[i]]$CardName))>0){
      archetypeURL = c(archetypeURL,df$AnchorUri[[i]])
    }
  }
  return(archetypeURL)
}

#' Get all URL of decks of a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the list URL of decks of a given archetype, provided in parameters.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getURLofDeck = function(deckName,df){
  return(df[df$Archetype$Archetype==deckName,]$AnchorUri)
}

#' Get the URL of the deck with the best win/loss ratio for a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the URL of the most successful deck of a given archetype.
#' The most successful is defined as having the highest difference between its
#' wins and defeats. A 7-0 is equivalent to a 10-3. Idea by Frank Karsten.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getBestDeck = function(deckName,df){
  df2=df[df$Archetype$Archetype==deckName,]
  df2$WinLossScore = df2$Wins - df2$Losses
  if(nrow(df2)>0){
    df2=df2[df2$WinLossScore==max(df2$WinLossScore),]
  }
  return(df2$AnchorUri)
}

#' Get the decklist of the deck with the best win/loss ratio for a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the URL of the most successful deck of a given archetype.
#' The most successful is defined as having the highest difference between its
#' wins and defeats. A 7-0 is equivalent to a 10-3. Idea by Frank Karsten.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getBestDeckList = function(deckName,df){
  df2=df[df$Archetype$Archetype==deckName,]
  df2$WinLossScore = df2$Wins - df2$Losses
  if(nrow(df2)>0){
    df2=df2[df2$WinLossScore==max(df2$WinLossScore),]
  }
  return(list(df2$Mainboard, df2$Sideboard))
}

#' Matchup data between two given archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param arch1 a string with the name of the archetype compared to the other
#' @param arch2 a string with the name of the archetype as opponent of the arch1
#'
#' @return a vector with the number of wins and losses in that matchup.
#' @export
#'
#' @examples
get_matchup_data = function(df,arch1,arch2){
  winsArch1VS2 = 0
  lossesArch1VS2 = 0
  dfArch1 = df[df$Archetype$Archetype==arch1,]
  conditionMUNotNull = !sapply(dfArch1$Matchups, function(x) length(x) == 0 )
  for (i in (1:nrow(dfArch1))[conditionMUNotNull]){
    matchesI = dfArch1[i,]$Matchups[[1]]
    matchesArch1VS2 = matchesI[matchesI$OpponentArchetype == arch2,]
    
    WinsI = matchesArch1VS2$Wins 
    DefeatsI = matchesArch1VS2$Losses 
    
    winsArch1VS2 = winsArch1VS2 + sum(WinsI > DefeatsI)
    lossesArch1VS2 = lossesArch1VS2 + sum(WinsI < DefeatsI) 
  }
  
  return(c(Wins = winsArch1VS2, Losses = lossesArch1VS2))
}

