################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                        02-Simple_Getters.R                           #####
##### Use this file to run simple getters on the imported data.            #####
################################################################################

# install.packages("readr")
# install.packages("devtools")
# install.packages("data.table")
# install.packages("knitr")
library("readr")
library("devtools")
library("data.table")
library("knitr")

#' Get conflicted archetype URL
#'
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of URL of archetypes with Conflicts
#' @export
#'
#' @examples
getConflictURL = function(df){
  return(df[startsWith(df$Archetype$Archetype,"Conflict")==TRUE,]$AnchorUri)
}

#' Get conflicted archetype names
#'
#' @param df the dataframe returned bygenerate_df()
#'
#' @return the list of names of archetypes with Conflicts
#' @export
#'
#' @examples
getConflictArchetype = function(df){
  return(df[startsWith(df$Archetype$Archetype,
                       "Conflict")==TRUE,]$Archetype$Archetype)
}

#' Get Unknown archetype URL
#'
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of URL of archetypes classified as Unknown
#' @export
#'
#' @examples
getUnknown = function(df){
  return(df[df$Archetype$Archetype=="Unknown",]$AnchorUri)
}

#' Get all URL of decks with a given card
#'
#' @param cardName a string with the name of the card to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the list of decks with a specific card in the data. 
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getURLofCard = function(cardName,df){
  archetypeURL = c()
  for (i in 1:nrow(df)){
    if (length(grep(cardName,df$Mainboard[[i]]$CardName)) + 
        length(grep(cardName,df$Sideboard[[i]]$CardName))>0){
      archetypeURL = c(archetypeURL,df$AnchorUri[[i]])
    }
  }
  return(archetypeURL)
}

#' Get all URL of decks of a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the list URL of decks of a given archetype, provided in parameters.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getURLofDeck = function(deckName,df){
  
  df2 = df[df$Archetype$Archetype == deckName,]
  df2$WinLossScore = df2$Wins - df2$Losses
  df2 = df2[order(df2$WinLossScore),]
  
  return(df2$AnchorUri)
}

#' Get the URL of the deck with the best win - loss ratio for a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the URL of the most successful deck of a given archetype.
#' The most successful is defined as having the highest difference between its
#' wins and defeats. A 7-0 is equivalent to a 10-3. Idea by Frank Karsten.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getBestDeck = function(deckName,df){
  df2 = df[df$Archetype$Archetype == deckName,]
  df2$WinLossScore = df2$Wins - df2$Losses
  if(nrow(df2)>0){
    df2 = df2[df2$WinLossScore == max(df2$WinLossScore),]
  }
  return(df2$AnchorUri)
}

#' Get the deck list(s) with the best win - loss ratio for a given archetype
#'
#' @param deckName a string with the name of the archetype to find
#' @param df the dataframe returned by generate_df()
#'
#' @return the deck list(s) of the most successful deck(s) of a given archetype.
#' The most successful is defined as having the highest difference between its
#' wins and defeats. A 7-0 is equivalent to a 10-3. Idea by Frank Karsten.
#' Empty if nothing fits (wrong name or not in the data).
#' @export
#'
#' @examples
getBestDeckList = function(deckName,df){
  df2 = df[df$Archetype$Archetype == deckName,]
  df2$WinLossScore = df2$Wins - df2$Losses
  if(nrow(df2)>0){
    df2 = df2[df2$WinLossScore == max(df2$WinLossScore),]
  }
  return(list(Mainboards = df2$Mainboard, Sideboards = df2$Sideboard))
}

#' Matchup data between two given archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param arch1 a string with the name of the archetype compared to the other
#' @param arch2 a string with the name of the archetype as opponent of the arch1
#'
#' @return a vector with the number of wins and losses in that matchup.
#' @export
#'
#' @examples
get_matchup_data = function(df,arch1,arch2){
  winsArch1VS2 = 0
  lossesArch1VS2 = 0
  dfArch1 = df[df$Archetype$Archetype==arch1,]
  conditionMUNotNull = !sapply(dfArch1$Matchups, function(x) length(x) == 0 )
  for (i in (1:nrow(dfArch1))[conditionMUNotNull]){
    matchesI = dfArch1[i,]$Matchups[[1]]
    matchesArch1VS2 = matchesI[matchesI$OpponentArchetype == arch2,]
    
    WinsI = matchesArch1VS2$Wins 
    DefeatsI = matchesArch1VS2$Losses 
    
    winsArch1VS2 = winsArch1VS2 + sum(WinsI > DefeatsI)
    lossesArch1VS2 = lossesArch1VS2 + sum(WinsI < DefeatsI) 
  }
  
  return(c(Wins = winsArch1VS2, Losses = lossesArch1VS2))
}

#' Different types of win rates for a given archetype
#'
#' @param df the dataframe returned by generate_df()
#' @param archetypeName a string with the name of the archetype
#'
#' @return a vector with the archetype name, the presence by copies and the
#' values for the different types of win rates and draws.
#' @export 
#'
#' @examples
getArchetypeWinRates = function(tournamentDf, archetypeName){
  
  archetypeDf = tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]
  
  archetypePresence = paste0(round(sum(archetypeDf$Wins)/nrow(tournamentDf),
                                   digits = 4) * 100,"%")
  archetypeWinRateWDraws = paste0(round(sum(archetypeDf$Wins)/
                                          sum(archetypeDf$Matches),
                                        digits = 4) * 100,"%")
  archetypeWinRateWoDraws = paste0(round(sum(archetypeDf$Wins)/
                                           (sum(archetypeDf$Wins) + 
                                              sum(archetypeDf$Losses)),
                                         digits = 4) * 100,"%")
  archetypeDrawPercentage = paste0(round(sum(archetypeDf$Draws)/
                                           sum(archetypeDf$Matches),
                                         digits = 4) * 100,"%")
  
  colLabels = c("Archetype Name",
                "Archetype Presence",
                "Archetype Win Rate w Draws", 
                "Archetype Win Rate w/o Draws",
                "Archetype Draw Percentage")
  
  archetypeData = c(archetypeName, 
                    archetypePresence, 
                    archetypeWinRateWDraws,
                    archetypeWinRateWoDraws, 
                    archetypeDrawPercentage)
  
  archetypeDF = t(data.frame(archetypeData))
  rownames(archetypeDF) = c()
  colnames(archetypeDF) = colLabels
  
  print(kable(archetypeDF))
  return(archetypeDF)
}

#' Print the win rate of a given archetype.
#'
#' @param df the dataframe returned by generate_df()
#' @param archetypeName a string with the name of the archetype
#'
#' @return 
#' @export
#'
#' @examples
getArchetypeWR = function(tournamentDf, archetypeName){
  archetypeDf = tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]
  paste("The win rate (w/o draws) of",archetypeName,"is:",
        round(100 * sum(archetypeDf$Wins)/
                (sum(archetypeDf$Wins) + 
                   sum(archetypeDf$Losses)),digits = 2),"%.")
}