################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                    03-Metagame_Graph_Generation.R                    #####
##### Use this file to import functions that will generate the classical   #####
##### metagame visualisation graphs.                                       #####
################################################################################

library(ggplot2)
library(ggrepel)

# # For development
# df = tournamentDf
# pieShare = PieShare
# barShare = BarShare
# presence = "Matches"
# beginning = Beginning
# end = End
# eventType = EventType
# mtgFormat = MTGFormat

#' Title of metagame share graphs
#'
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name 
#' @param mtgFormat the format of the events in the data
#'
#' @return
#' @export
#'
#' @examples
generate_metagame_graph_title = 
  function(presence, beginning, end, eventType, mtgFormat){
    return(paste0("Metagame share of ", mtgFormat ," archetypes in ", 
                 eventType," between\n", beginning, " and ", end,
                 " based on number of ", presence))
  }

#' Pie chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param pieShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use pieShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a pie chart representing the most played archetypes,
#' including a part for all the undisplayed archetypes in the data, labeled as
#' "Other (each <pieShare%)".
#' @export
#'
#' @examples
metagame_pie_chart = function(df, pieShare = PieShare, presence = "Matches",
                              beginning = Beginning, end = End,
                              eventType = EventType, mtgFormat = MTGFormat){
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,pieShare,presence)
  
  positions_df = metagame_df %>% 
    mutate(csum = rev(cumsum(rev(-Share))), 
           position = -Share/2 + lead(csum, 1),
           position = if_else(is.na(position), -Share/2, position))
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  ggplot(metagame_df, 
         aes(x="", -Share, fill = Archetype))  + 
    geom_label_repel(data = positions_df, 
                     aes(y = position, label = paste0(Archetype,"\n",Share,"%"),
                         fill = Archetype), size = 4, nudge_x = 0.9,
                     show.legend = FALSE,
                     max.overlaps = getOption("ggrepel.max.overlaps", 
                                              default = nrow(metagame_df))) +
    geom_bar(width = 1, linewidth = 0.2, color = "white", stat = "identity") + 
    coord_polar("y", start=0) +
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111",size = 20),
          plot.subtitle = element_text(hjust = 0.5,size = 18),
          panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = "none") + 
    labs(x = NULL, y = NULL, fill = NULL, subtitle = "by Anaël Yahi",
         title = generate_metagame_graph_title(
           presence, beginning, end, eventType, mtgFormat)) + 
    guides(color = FALSE, size = FALSE) +
    scale_color_gradient(low="red", high="blue")
  
}

#' Bar chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param barShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use pieShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a bar chart representing the most played archetypes.
#' @export
#'
#' @examples
metagame_bar_chart = 
  function(df,barShare,presence,beginning,end,eventType,mtgFormat){
  
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,histShare,presence)
  # Remove the "Other" category
  metagame_df = metagame_df[!grepl("Other",metagame_df$Archetype),]
  # Reorder archetypes by ascending presence
  metagame_df$Archetype = reorder(metagame_df$Archetype, 
                                  as.numeric(metagame_df$Presence))
  
  # Generate a title
  bar_chart_title=paste(generate_metagame_graph_title(
    presence,beginning,end,eventType,mtgFormat),
    "\nArchetype cut at",histShare,"%")
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  #plot is much clearer
  ggplot(metagame_df, aes(x=Archetype, y=as.numeric(Share), fill=Archetype)) + 
    geom_bar(stat="identity") + theme_minimal() + guides( fill = FALSE) +
    geom_text(aes(label = paste0(Share, "%")), hjust = 1.5, size = 4) +
    labs(x = NULL, y = NULL, fill = NULL, 
         title = bar_chart_title, subtitle = "by Anaël Yahi") + 
    scale_color_gradient(low="red", high="blue") + coord_flip() +
    scale_y_continuous(limits = c(0,nrow(metagame_df)), expand = c(0.01, 0)) +
    theme(plot.title = element_text(hjust = 0.5, color = "#111111",size = 20),
          plot.subtitle = element_text(hjust = 0.5,size = 18),
          panel.background = element_blank(),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          text = element_text(size=16))
}