################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                    03-Metagame_Graph_Generation.R                    #####
##### Use this file to import functions that will generate the usual       #####
##### metagame visualisation graphs.                                       #####
################################################################################

library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(ggtext)
library(paletteer)

# # For development
# df = tournamentDf
# chartShare = ChartShare
# statShare = StatShare
# presence = "Matches"
# beginning = Beginning
# end = End
# eventType = EventType
# mtgFormat = MtgFormat
# diameters = "Players"
# presenceAxisLogScale = T
# archetypeMetricsDf = archetype_metrics(df)
# archetypeRankingDf = archetype_ranking(archetypeMetricsDf,presence)
# archetypeTiersDf = archetype_tiers(archetypeRankingDf, presence, chartShare)

#' Title of metagame share graphs
#'
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name 
#' @param mtgFormat the format of the events in the data
#'
#' @return
#' @export
#'
#' @examples
generate_metagame_graph_title = 
  function(presence, beginning, end, eventType, mtgFormat){
    return(paste0("Metagame share of ", mtgFormat ," archetypes in ", 
                 eventType," between\n", beginning, " and ", end,
                 " based on number of ", presence))
  }

#' Pie chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a pie chart representing the most played archetypes,
#' including a part for all the undisplayed archetypes in the data, labeled as
#' "Other (each <chartShare%)".
#' @export
#'
#' @examples
metagame_pie_chart = function(df, chartShare, presence, beginning, end,
                              eventType, mtgFormat){
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,chartShare,presence)
  
  positions_df = metagame_df %>% 
    mutate(csum = rev(cumsum(rev(-Share))), 
           position = -Share/2 + lead(csum, 1),
           position = if_else(is.na(position), -Share/2, position))
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  ggplot(metagame_df, aes(x="", -Share, fill = Archetype))  + 
    
    geom_bar(width = 1, linewidth = 0.2, color = "white", stat = "identity") + 
    
    coord_polar("y", start = 0)  +
    
    geom_text(aes(label = paste0(Share, "%"), x = 1.35), size=3, 
              position = position_stack(vjust = 0.5)) + 
    
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111",size = 18),
          plot.subtitle = element_text(hjust = 0.5,size = 16),
          panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank()) + 
    
    labs(x = NULL, y = NULL, fill = NULL, subtitle = "by Anaël Yahi",
         title = generate_metagame_graph_title(
           presence, beginning, end, eventType, mtgFormat)) + 
    
    guides(color = FALSE, size = FALSE, scale = "none")
}

#' Bar chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a bar chart representing the most played archetypes.
#' @export
#'
#' @examples
metagame_bar_chart = 
  function(df,chartShare,presence,beginning,end,eventType,mtgFormat){
  
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,chartShare,presence)
  # Remove the "Other" category
  metagame_df = metagame_df[!grepl("Other",metagame_df$Archetype),]
  # Reorder archetypes by ascending presence
  metagame_df$Archetype = reorder(metagame_df$Archetype, 
                                  as.numeric(metagame_df$Presence))
  
  # Generate a title
  bar_chart_title=paste(generate_metagame_graph_title(
    presence,beginning,end,eventType,mtgFormat),
    "\nArchetype cut at",chartShare,"%")
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  #plot is much clearer
  ggplot(metagame_df, aes(x=Archetype, y=as.numeric(Share), fill=Archetype)) + 
    
    geom_bar(stat="identity") + theme_minimal() + guides( fill = FALSE) +
    
    geom_text(aes(label = paste0(Share, "%")), hjust = 1.1, size = 4) +
    
    labs(x = NULL, y = NULL, fill = NULL, 
         title = bar_chart_title, subtitle = "by Anaël Yahi") + 
    
    coord_flip() +
    
    scale_y_continuous(limits = c(0,max(metagame_df$Share)*1.1), expand = c(0.01, 0)) +
    
    theme(plot.title = element_text(hjust = 0.5, color = "#111111",size = 18),
          plot.subtitle = element_text(hjust = 0.5,size = 16),
          axis.line.x=element_line(color="black"),
          axis.line.y=element_line(color="black"),
          panel.background = element_blank(),
          text = element_text(size=16),
          plot.title.position = "plot") 

  }

#' Win rate and their confidence intervals for the most played archetypes
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#' @param sortValue the value used for sorting the data in the graph.
#' It can be either "MeasuredWinrate" or "CI95LowerBound" (the lower bound of
#' the 95% confidence interval on the win rate).
#'
#' @return a ggplot with the win rate and the confidence intervals.
#' @export
#'
#' @examples
winrates_graph = function(archetypeRankingDf,chartShare,presence,beginning,end,
                          eventType,mtgFormat,sortValue){
  
  # Keep only the most present decks
  presence_min = chartShare/100*sum(archetypeRankingDf[presence])
  most_present_archetypes = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  # Reorder archetypes by ascending average winrate
  most_present_archetypes$Archetype = 
    reorder(most_present_archetypes$Archetype, unlist(most_present_archetypes[sortValue]))
  
  # Plot the average winrate and the confidence intervals
  yLabelWinrate = "Winrates of the most popular archetypes (%)"
  
  winrateGraphTitle = paste0(
    CIPercent*100,"% confidence intervals on the winrates of the most present ",mtgFormat,
    " archetypes\n",  "(at least ",chartShare,"% of the ",presence,") between ", 
    beginning, " and ", end, " in ", EventType)
  
  winrateGraphSubtitle = 
  paste("Red lines for the average of the bounds of the CI",
        "Green line for the average of the measured winrate", 
        "by Anaël Yahi", sep = "\n")
  
  ggplot(most_present_archetypes, aes(x = Archetype, y = MeasuredWinrate)) + 
    
    geom_point(size = 2, color = "blue") +  
    
    geom_text_repel(aes(label = format(round(MeasuredWinrate, 1), nsmall = 1)), 
      hjust = -0.3, vjust = -0.3, point.padding = NA) + 
    
    labs(x = NULL, y = yLabelWinrate, title = winrateGraphTitle,
         subtitle = winrateGraphSubtitle) +
    
    theme(axis.text.x = element_text(size = 10, 
                                     angle = -nrow(most_present_archetypes)),
          axis.title.y = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), 
                         size=14, face = "bold"),
          panel.background = element_blank(),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black"),
          axis.ticks.y = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111", size = 16),
          plot.subtitle = element_text(hjust = 0.5, size = 14),
          text = element_text(size = 16)) + 
    
    geom_errorbar(aes(ymax = CI95UpperBound, ymin = CI95LowerBound)) + 
    
    geom_hline(yintercept = mean(most_present_archetypes$MeasuredWinrate), 
               color="green", linetype="dashed", linewidth = 1)+ 
    
    geom_hline(yintercept = mean(most_present_archetypes$CI95LowerBound), 
               color="red", linetype="dashed", linewidth = 0.5)+ 
    
    geom_hline(yintercept = mean(most_present_archetypes$CI95UpperBound), 
               color="red", linetype="dashed", linewidth = 0.5)
}

#' Win rate and their boxplots for the most played archetypes
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param tournamentDf the dataframe returned by generate_df()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#' @param sortValue the value used for sorting the data in the graph.
#' It can be either "MeasuredWinrate" or "CI95LowerBound" (the lower bound of
#' the 95% confidence interval on the win rate).
#'
#' @return a ggplot with a boxplot of the winrates.
#' @export
#'
#' @examples
boxplot_winrates = function(archetypeRankingDf,tournamentDf,chartShare,presence,beginning,end,
                            eventType,mtgFormat,sortValue){
  
  chartShare = StatShare
  presence = Presence
  beginning = Beginning
  end = End
  eventType = EventType
  mtgFormat = MtgFormat
  sortValue = SortValue
  # Keep only the most present decks
  presence_min = chartShare/100*sum(archetypeRankingDf[presence])
  most_present_archetypes_data = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  # Reorder archetypes by ascending average winrate
  most_present_archetypes_data$Archetype = 
    reorder(most_present_archetypes_data$Archetype, unlist(most_present_archetypes_data[sortValue]))
  
  most_present_archetypes = most_present_archetypes_data$Archetype
  
  most_present_archetypes_df = tournamentDf[tournamentDf$Archetype$Archetype %in% 
                                              most_present_archetypes,] %>% 
    select(c('Archetype','NWins','NDefeats'))
  
  most_present_archetypes_df$Archetype = most_present_archetypes_df$Archetype$Archetype
  
  most_present_archetypes_df$Winrate = 100 * most_present_archetypes_df$NWins / 
    (most_present_archetypes_df$NWins + most_present_archetypes_df$NDefeats)
  most_present_archetypes_df$WinrateLabel = paste0(round(most_present_archetypes_df$Winrate,digits=1),"%")
  
  # Plot the average winrate and the confidence intervals
  yLabelWinrate = "Winrates of the most popular archetypes (%)"
  
  winrateGraphTitle = paste0(
  "Winrate repartition of the most present ",mtgFormat,
    " archetypes\n",  "(at least ",chartShare,"% of the ",presence,") between ", 
    beginning, " and ", end, " in ", EventType)
  
  winrateGraphSubtitle = 
    paste("Blue points for the average of the measured winrate", 
          "by Anaël Yahi", sep = "\n")
  
  p <- ggplot(most_present_archetypes_df, aes(x=reorder(Archetype,Winrate), y=Winrate)) + 
    geom_boxplot() + 
    labs(x = NULL, y = yLabelWinrate, title = winrateGraphTitle,
         subtitle = winrateGraphSubtitle)  +
    stat_summary(fun=mean, geom="point", shape=20, size=4, color="blue", fill="blue") +  # Add points to plot
    stat_summary(fun = mean, geom = "text", col = "black", size = 4,     # Add text to plot
                 vjust = 1.5, hjust = 0.5, aes(label = paste0(round(..y.., digits = 1),"%"))) +
    theme(axis.text.x = element_text(size = 10, vjust = 0.5, 
                                     angle = -90+nrow(archetypeRankingDf)),
          axis.title.y = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), 
                         size=14, face = "bold"),
          panel.background = element_blank(),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black"),
          axis.ticks.y = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111", size = 16),
          plot.subtitle = element_text(hjust = 0.5, size = 14),
          text = element_text(size = 16)) 
  
  p

}

#' Graph of the archetype tier list based on normalized sum of metrics
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot showing all the scores of the normalized sum of metrics, and
#' the tier list generated accordingly.
#' @export
#'
#' @examples
normalized_sum_graph = function(archetypeRankingDf,chartShare,presence,
                                beginning,end,eventType,mtgFormat){
  
  # Keep only the most present decks
  presence_min = chartShare/100*sum(archetypeRankingDf[presence])
  most_present_archetypes = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  meanData = mean(most_present_archetypes$NormalizedSum)
  sdData = sd(most_present_archetypes$NormalizedSum)
  meanPlusSd = meanData + sdData
  meanMinusSd = meanData - sdData
  
  most_present_archetypes$Archetype=reorder(most_present_archetypes$Archetype,
                                     most_present_archetypes$NormalizedSum)
  
  normalizedSumGraphTitle = paste0(
    "Sum of the normalized metrics of the most present ",mtgFormat,
    " archetypes\n",  "(at least ",chartShare,"% of the ",presence,") between ", 
    beginning, " and ", end, " in ", EventType)
  
  normalizedSumGraphSubtitle = "by Anaël Yahi"
  
  xDodge = 0
  yDodgeTierExplanation = 0.01
  sizeHline = 1
  sizeTierNameText = 8
  sizeTierExplanationText = 6
  
  ggplot(most_present_archetypes, aes(x = Archetype, y = NormalizedSum)) +
    
    geom_point(size=4,color="blue") +  
    
    geom_text_repel(aes(label=format(round(NormalizedSum,2), nsmall = 2)), 
                    hjust = -0.3, vjust = -0.2, point.padding = NA, size = 6,
                    min.segment.length = Inf) + 
    
    labs(x = NULL, y = "Value of the normalized sum metric", 
         title = normalizedSumGraphTitle,
         subtitle = normalizedSumGraphSubtitle) + 
    
    theme(axis.text.x = 
            element_text(angle = - nrow(most_present_archetypes), size = 20),
          axis.text.y = element_text(size = 20),
          axis.title.y = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0), 
                         size = 30, face = "bold"),
          panel.background = element_blank(),
          axis.ticks.y = element_blank(),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black"),
          plot.title = element_text(hjust = 0.5, color = "#111111", size = 30),
          plot.subtitle = element_text(hjust = 0.5, size = 24)) +
    
    #Add tier list lines and labels
    geom_hline(yintercept = meanData - 3 * sdData, color = "#004CA3", 
               linetype="dashed", linewidth = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - 3 * sdData, label = "Tier 3\n"), 
              colour = "#004CA3", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData -3 * sdData - yDodgeTierExplanation,
                  label = "Mean - 3*SD"), colour = "grey", 
              size = sizeTierExplanationText) + 
    
    geom_hline(yintercept = meanData - 2 * sdData, color = "#8A51A5", 
               linetype = "dashed", linewidth = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - 2 * sdData, label = "Tier 2.5\n"), 
              colour = "#8A51A5", size = sizeTierNameText) + 
    geom_text(aes(x = xDodge, y = meanData - 2 * sdData - yDodgeTierExplanation, 
                  label = "Mean - 2*SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData - sdData, color = "#CB5E99", 
               linetype = "dashed", linewidth = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - sdData, label = "Tier 2\n"), 
              colour = "#CB5E99", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData - sdData - yDodgeTierExplanation,
                  label = "Mean - SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData, color = "#F47B89", linetype = "dashed", 
               linewidth = sizeHline)+
    geom_text(aes(x = xDodge, y = meanData, label = "Tier 1.5\n"), 
              colour = "#F47B89", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData - yDodgeTierExplanation, 
                  label = "Mean"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData+sdData, color = "#FFA47E", 
               linetype = "dashed", linewidth = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + sdData, label = "Tier 1\n"),
              colour="#FFA47E", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + sdData - yDodgeTierExplanation,
                  label = "Mean + SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData + 2 * sdData, color="#FFD286", 
               linetype="dashed", linewidth = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + 2 * sdData, label = "Tier 0.5\n"), 
              colour = "#FFD286", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + 2 * sdData - yDodgeTierExplanation,
                  label="Mean + 2*SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData + 3 * sdData, color="#90EE90", 
               linetype = "dashed", linewidth = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + 3 * sdData, label = "Tier 0\n"), 
              colour = "#90EE90", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + 3 * sdData - yDodgeTierExplanation,
                  label = "Mean + 3*SD"), colour = "grey", 
              size = sizeTierExplanationText) + 
    # Added to update enlarge the frame of the graph so the text is not cut
    geom_text(aes(x = xDodge - 1, y = meanData, label = ""))
}


#' Detailed 2D view of the win rate and presence of the most present decks
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#' @param presenceAxisLogScale draw the presence axis with a linear scale if TRUE
#'
#' @return a ggplot in two dimensions displaying the presence and win rate of 
#' the most present archetypes, including the detail in labels, in addition to
#' their tiers with different colors
#' @export
#'
#' @examples
detailed_winrate_and_presence_graph = 
  function (archetypeTiersDf,chartShare,presence, beginning,end,eventType,
            mtgFormat,presenceAxisLogScale){
  # Keep only the most present decks and compute their tiers
  
    archetypeTiersDf$Label = paste0(archetypeTiersDf$Archetype,
                                  "\nPresence: ",
                                  round(archetypeTiersDf$Presence, 
                                        digits = 1)
                                  ,"%\nWin rate: ",
                                  round(archetypeTiersDf$MeasuredWinrate,
                                        digits = 1),"%")
  
  x_label = "Presence (%)"
  y_label = "Win rate (%)"
  graph_title=paste0("Win rates depending on presence of the most present ",
                     mtgFormat, " archetypes\n(at least ",chartShare,
                     "% of the ", presence,") between ", beginning, " and ",
                     end, " in ", eventType)
  graph_subtitle=paste("by Anaël Yahi")
  
  winrate_and_presence_plot_focused =
    ggplot(archetypeTiersDf, aes(x = Presence, y = MeasuredWinrate, 
                               color = Tiers, label = Label)) +
    
    # scale_color_gradient(low="blue", high="red") +
    
    coord_cartesian() +
    
    labs(x = x_label, y = y_label, title = graph_title, 
         subtitle = graph_subtitle) + 
    
    geom_label_repel(box.padding = 0.5, nudge_x = c(-0.05, 0.05),
                     min.segment.length = 0) +
    
    theme(panel.background = element_blank(),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black"),
          axis.text = element_text(size = 20),
          axis.title = 
            element_text(margin = margin(t = 0, r = 40, b = 0, l = 0), 
                         size = 24, face = "bold"),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111",size = 28),
          plot.subtitle = element_text(hjust = 0.5,size = 24),
          legend.title = element_text(size = 20),
          legend.text = element_text(size = 18)) +
    
  geom_point(aes(size=Players)) 
  
  if (presenceAxisLogScale){
    winrate_and_presence_plot_focused = 
      winrate_and_presence_plot_focused + scale_x_continuous(trans = 'log10')
  }
  
  winrate_and_presence_plot_focused
}

#' Detailed 2D view of the win rate and presence of the most present decks
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param diameters the metagame presence metric used for the points size. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype 
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#' @param presenceAxisLogScale draw the presence axis with a linear scale if TRUE
#'
#' @return a ggplot in two dimensions displaying the presence and win rate of 
#' the most present archetypes, with points changing size depending on a chosen
#' type of presence.
#' @export
#'
#' @examples
simple_winrate_and_presence_graph = 
  function(archetypeRankingDf,chartShare,presence,diameters,beginning,end,
           eventType,mtgFormat,presenceAxisLogScale) {
  
    archetypeTiersDf = archetype_tiers(archetypeRankingDf, presence, chartShare)

  average = mean(archetypeTiersDf$MeasuredWinrate)
  sdeviation = sd(archetypeTiersDf$MeasuredWinrate)
  
  x_label = ifelse(presence=="Copies",
                   "Number of copies of each archetype (%)",
                   ifelse(presence=="Players",
                          "Number of different players for each archetype (%)",
                          ifelse(presence=="Matches",
                                 "Number of matches for each archetype (%)",
                                 NA
                          )))
  
  y_label="Average winrate of each archetype (%)"
  
  graph_title = paste0("Win rates depending on presence (",presence,") of ",
                     mtgFormat, " archetypes\nbetween ", beginning, " and ",
                     end, " in ", eventType)
  
  graph_subtitle=paste("Circle diameters depending on",diameters,
                       "\nby Anaël Yahi")
  
  avg_presence = mean(archetypeTiersDf$Presence)
  sd_presence = sd(archetypeTiersDf$Presence)
  
  metric_plot = ggplot(archetypeTiersDf, aes(Presence, MeasuredWinrate)) +
    
    geom_point(aes(color = Archetype), 
               size = archetypeTiersDf$Presence/
                 max(archetypeTiersDf$Presence) * 25,
               show.legend = FALSE) + 
    
    coord_cartesian() + 
    
    theme(panel.background = element_blank(),
          axis.line.x=element_line(color="black"),
          axis.line.y=element_line(color="black"),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          axis.text = element_text(size = 16),
          axis.title = 
            element_text(margin = margin(t = 0, r = 80, b = 0, l = 0), 
                         size = 20, face = "bold"),
          plot.title = element_text(hjust = 0.5, color = "#111111",size = 28),
          plot.subtitle = element_text(hjust = 0.5, size = 24)) + 
    
    labs(x = x_label, y = y_label, title=graph_title, subtitle=graph_subtitle) +
    
    geom_text_repel(aes(label=Archetype), hjust = 0, vjust = 0, 
                    point.padding = NA, size = 3, nudge_x = 0.1, direction = "y",
                    segment.size = 0.2, segment.color="dark grey", 
                    segment.alpha = 0.8) 
  
  if (presenceAxisLogScale){
    metric_plot = metric_plot + scale_x_continuous(trans = 'log10')
  }
  
  metric_plot
  
  }

#' Win rate matrix of the most present archetypes
#'
#' @param muMatrixData the dataframe generated by generate_matchup_data()
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return ggplot with a 2D table presenting the matchup results between all the
#' main archetypes
#' @export
#'
#' @examples
generate_matchup_matrix = function(muMatrixData,chartShare,presence,beginning,
                                   end,mtgFormat,eventType){
  
  MUMatrixTitle = paste0("Match Up Matrix of the most present ",  mtgFormat, 
                     " archetypes\n(at least ", min(muMatrixData$Share), 
                     "% of the ",  presence,") between ", beginning, " and ", 
                     end, " in ",  eventType)
  
  MUMatrixSubtitle = 
    paste("Win rate of Y (ordinates) against X (abscissa)", 
          "by Anaël Yahi", sep = "\n")
  
  if(length(unique(muMatrixData$Archetype1))>1){
    MUMatrixPlot = ggplot(muMatrixData,aes(x = Archetype2, 
                                           y = reorder(ArchShare1,-DisplayOrder), 
                                           col = MUWinrate, fill = MUWinrate, 
                                           label = OutputText))
  }else{
    MUMatrixPlot = ggplot(muMatrixData,aes(x = Archetype2, 
                                           y = unique(Archetype1),
                                           col = MUWinrate, 
                                           fill = MUWinrate, label = OutputText))
  }
  
  MUMatrixPlot = MUMatrixPlot + 
    
    theme(panel.background = element_blank(),
          axis.text.x = element_text(face="bold", size=11, angle = -10),
          axis.text.y = element_markdown(),
          legend.position = "none",
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5)) + 
    
    scale_fill_gradientn(
      colours = paletteer_c("ggthemes::Red-Green-Gold Diverging", 30)) +
    
    scale_x_discrete(position = "top") +
    
    labs(x=NULL, y=NULL, title = MUMatrixTitle, subtitle = MUMatrixSubtitle) +
    
    geom_tile(color = "black",lwd = 0.5,linetype = 1) +
    
    geom_richtext( fill = NA, label.color = NA, # remove background and outline
                   label.padding = grid::unit(rep(0, 4), "pt"), # remove padding
                   color = "black") 
  
  
  
  MUMatrixPlot
}
