################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                    03-Metagame_Graph_Generation.R                    #####
##### Use this file to import functions that will generate the classical   #####
##### metagame visualisation graphs.                                       #####
################################################################################

library(ggplot2)
library(ggrepel)
library(ggtext)

# # For development
# df = tournamentDf
# pieShare = PieShare
# barShare = BarShare
# presence = "Matches"
# beginning = Beginning
# end = End
# eventType = EventType
# mtgFormat = MTGFormat
archetypeMetricsDf = archetype_metrics(df)
archetypeRankingDf = archetype_ranking(archetypeMetricsDf,presence)

#' Title of metagame share graphs
#'
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name 
#' @param mtgFormat the format of the events in the data
#'
#' @return
#' @export
#'
#' @examples
generate_metagame_graph_title = 
  function(presence, beginning, end, eventType, mtgFormat){
    return(paste0("Metagame share of ", mtgFormat ," archetypes in ", 
                 eventType," between\n", beginning, " and ", end,
                 " based on number of ", presence))
  }

#' Pie chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param pieShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use pieShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a pie chart representing the most played archetypes,
#' including a part for all the undisplayed archetypes in the data, labeled as
#' "Other (each <pieShare%)".
#' @export
#'
#' @examples
metagame_pie_chart = function(df, pieShare = PieShare, presence = "Matches",
                              beginning = Beginning, end = End,
                              eventType = EventType, mtgFormat = MTGFormat){
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,pieShare,presence)
  
  positions_df = metagame_df %>% 
    mutate(csum = rev(cumsum(rev(-Share))), 
           position = -Share/2 + lead(csum, 1),
           position = if_else(is.na(position), -Share/2, position))
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  ggplot(metagame_df, 
         aes(x="", -Share, fill = Archetype))  + 
    geom_label_repel(data = positions_df, 
                     aes(y = position, label = paste0(Archetype,"\n",Share,"%"),
                         fill = Archetype), size = 4, nudge_x = 0.9,
                     show.legend = FALSE,
                     max.overlaps = getOption("ggrepel.max.overlaps", 
                                              default = nrow(metagame_df))) +
    geom_bar(width = 1, linewidth = 0.2, color = "white", stat = "identity") + 
    coord_polar("y", start=0) +
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = 0.5, color = "#111111",size = 20),
          plot.subtitle = element_text(hjust = 0.5,size = 18),
          panel.background = element_rect(fill = "white"),
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          legend.position = "none") + 
    labs(x = NULL, y = NULL, fill = NULL, subtitle = "by Anaël Yahi",
         title = generate_metagame_graph_title(
           presence, beginning, end, eventType, mtgFormat)) + 
    guides(color = FALSE, size = FALSE) +
    scale_color_gradient(low="red", high="blue")
  
}

#' Bar chart of the most played archetypes
#'
#' @param df the dataframe returned by generate_df()
#' @param barShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use pieShare=2 (not 0.02).
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot of a bar chart representing the most played archetypes.
#' @export
#'
#' @examples
metagame_bar_chart = 
  function(df,barShare,presence,beginning,end,eventType,mtgFormat){
  
  # Get the necessary data for the graph
  metagame_df = generate_metagame_data(df,histShare,presence)
  # Remove the "Other" category
  metagame_df = metagame_df[!grepl("Other",metagame_df$Archetype),]
  # Reorder archetypes by ascending presence
  metagame_df$Archetype = reorder(metagame_df$Archetype, 
                                  as.numeric(metagame_df$Presence))
  
  # Generate a title
  bar_chart_title=paste(generate_metagame_graph_title(
    presence,beginning,end,eventType,mtgFormat),
    "\nArchetype cut at",histShare,"%")
  
  # Another nice color palette
  # library(RColorBrewer)
  # Spectral goes up to 11. Staying at 9 removes dark red and purple.
  #graph_colors = colorRampPalette(brewer.pal(9, "Spectral"))(nrow(metagame_df))
  # scale_fill_manual(values = graph_colors) +
  
  #plot is much clearer
  ggplot(metagame_df, aes(x=Archetype, y=as.numeric(Share), fill=Archetype)) + 
    geom_bar(stat="identity") + theme_minimal() + guides( fill = FALSE) +
    geom_text(aes(label = paste0(Share, "%")), hjust = 1.5, size = 4) +
    labs(x = NULL, y = NULL, fill = NULL, 
         title = bar_chart_title, subtitle = "by Anaël Yahi") + 
    scale_color_gradient(low="red", high="blue") + coord_flip() +
    scale_y_continuous(limits = c(0,nrow(metagame_df)), expand = c(0.01, 0)) +
    theme(plot.title = element_text(hjust = 0.5, color = "#111111",size = 20),
          plot.subtitle = element_text(hjust = 0.5,size = 18),
          panel.background = element_blank(),
          # panel.grid.major = element_blank(), 
          # panel.grid.minor = element_blank(),
          text = element_text(size=16))
  }



#' Win rate and their confidence intervals for the most played archetypes
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param pieShare the value of the cut to be set in "Others" for an archetype.
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#' @param sortValue the value used for sorting the data in the graph.
#' It can be either "MeasuredWinrate" or "CI95LowerBound" (the lower bound of
#' the 95% confidence interval on the win rate).
#'
#' @return a ggplot with the win rate and the confidence intervals.
#' @export
#'
#' @examples
winrates_graph = function(archetypeRankingDf,pieShare,presence,beginning,end,
                          eventType,mtgFormat,sortValue){
  
  # Keep only the most present decks
  presence_min = pieShare/100*sum(archetypeRankingDf[presence])
  arch_most_played = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  # Reorder archetypes by ascending average winrate
  arch_most_played$Archetype = 
    reorder(arch_most_played$Archetype, unlist(arch_most_played[sortValue]))
  
  # Plot the average winrate and the confidence intervals
  yLabelWinrate = "Winrates of the most popular archetypes (%)"
  
  winrateGraphTitle = paste0(
    "Confidence intervals on the winrates of the most present ",mtgFormat,
    " archetypes\n",  "(at least ",pieShare,"% of the ",presence,") between ", 
    beginning, " and ", end, " in ", EventType)
  
  winrateGraphSubtitle = 
  paste("Red lines for the average of the bounds of the CI",
        "Green line for the average of the measured winrate", 
        "by Anaël Yahi", sep = "\n")
  
  ggplot(arch_most_played, aes(x=Archetype, y=MeasuredWinrate*100)) + 
    geom_point(size=2, color = "blue") +  
    geom_text_repel(aes(label = format(round(
      MeasuredWinrate*100,1), nsmall = 1)), 
      hjust = -0.3, vjust = -0.3, point.padding = NA) + 
    labs(x = NULL, y = yLabelWinrate, title = winrateGraphTitle,
         subtitle = winrateGraphSubtitle) +
    theme(axis.text.x = element_text(angle = -nrow(arch_most_played)),
          axis.title.y = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
          panel.background = element_blank(),
          axis.ticks.y = element_blank(),
          text = element_text(size = 16)) + 
    geom_errorbar(aes(ymax = CI95UpperBound *100, ymin = CI95LowerBound*100)) + 
    geom_hline(yintercept = mean(arch_most_played$MeasuredWinrate*100), 
               color="green", linetype="dashed", size=1)+ 
    geom_hline(yintercept = mean(arch_most_played$CI95LowerBound*100), 
               color="red", linetype="dashed", size=0.5)+ 
    geom_hline(yintercept = mean(arch_most_played$CI95UpperBound*100), 
               color="red", linetype="dashed", size=0.5) + 
    theme(axis.text.x  = element_text(size=12)) 
}


#' Graph of the archetype tier list based on normalized sum of metrics
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param pieShare the value of the cut to be set in "Others" for an archetype.
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return a ggplot showing all the scores of the normalized sum of metrics, and
#' the tier list generated accordingly.
#' @export
#'
#' @examples
normalized_sum_graph = function(archetypeRankingDf,pieShare,presence,beginning,end,
                            eventType,mtgFormat){
  
  # Keep only the most present decks
  presence_min = pieShare/100*sum(archetypeRankingDf[presence])
  arch_most_played = 
    archetypeRankingDf[archetypeRankingDf[presence] >= presence_min,]
  
  meanData = mean(arch_most_played$NormalizedSum)
  sdData = sd(arch_most_played$NormalizedSum)
  meanPlusSd = meanData + sdData
  meanMinusSd = meanData - sdData
  
  arch_most_played$Archetype=reorder(arch_most_played$Archetype,
                                     arch_most_played$NormalizedSum)
  
  normalizedSumGraphTitle = paste0(
    "Sum of the normalized metrics of the most present ",mtgFormat,
    " archetypes\n",  "(at least ",pieShare,"% of the ",presence,") between ", 
    beginning, " and ", end, " in ", EventType)
  
  normalizedSumGraphSubtitle = "by Anaël Yahi"
  
  xDodge = 0
  yDodgeTierExplanation = 0.01
  sizeHline = 1
  sizeTierNameText = 5
  sizeTierExplanationText = 4
  
  ggplot(arch_most_played, aes(x=Archetype, y=NormalizedSum)) + 
    theme_classic() + geom_point(size=4,color="blue") +  
    geom_text_repel(aes(label=format(round(NormalizedSum,2), nsmall = 2)), 
                    hjust = -0.3, vjust = -0.3, point.padding = NA, size = 5) + 
    labs(x=NULL, y="Value of the normalized sum metric", 
         title = normalizedSumGraphTitle,
         subtitle = normalizedSumGraphSubtitle) + 
    theme(axis.text.x = element_text(angle = -nrow(arch_most_played), size = 12)) +
    
    #Add tier list lines and labels
    geom_hline(yintercept = meanData - 3 * sdData, color = "#004CA3", 
               linetype="dashed", size = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - 3 * sdData, label = "Tier 3\n"), 
              colour = "#004CA3", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData -3 * sdData - yDodgeTierExplanation,
                  label = "Mean - 3*SD"), colour = "grey", 
              size = sizeTierExplanationText) + 
    
    geom_hline(yintercept = meanData - 2 * sdData, color = "#8A51A5", 
               linetype = "dashed", size = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - 2 * sdData, label = "Tier 2.5\n"), 
              colour = "#8A51A5", size = sizeTierNameText) + 
    geom_text(aes(x = xDodge, y = meanData - 2 * sdData - yDodgeTierExplanation, 
                  label = "Mean - 2*SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData - sdData, color = "#CB5E99", 
               linetype = "dashed", size = sizeHline) +
    geom_text(aes(x = xDodge, y = meanData - sdData, label = "Tier 2\n"), 
              colour = "#CB5E99", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData - sdData - yDodgeTierExplanation,
                  label = "Mean - SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData, color = "#F47B89", linetype = "dashed", 
               size = sizeHline)+
    geom_text(aes(x = xDodge, y = meanData, label = "Tier 1.5\n"), 
              colour = "#F47B89", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData - yDodgeTierExplanation, 
                  label = "Mean"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData+sdData, color = "#FFA47E", 
               linetype = "dashed", size = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + sdData, label = "Tier 1\n"),
              colour="#FFA47E", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + sdData - yDodgeTierExplanation,
                  label = "Mean + SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData + 2 * sdData, color="#FFD286", 
               linetype="dashed", size = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + 2 * sdData, label = "Tier 0.5\n"), 
              colour = "#FFD286", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + 2 * sdData - yDodgeTierExplanation,
                  label="Mean + 2*SD"), colour = "grey", 
              size = sizeTierExplanationText) +
    
    geom_hline(yintercept = meanData + 3 * sdData, color="#90EE90", 
               linetype = "dashed", size = sizeHline) + 
    geom_text(aes(x = xDodge, y = meanData + 3 * sdData, label = "Tier 0\n"), 
              colour = "#90EE90", size = sizeTierNameText) +
    geom_text(aes(x = xDodge, y = meanData + 3 * sdData - yDodgeTierExplanation,
                  label = "Mean + 3*SD"), colour = "grey", 
              size = sizeTierExplanationText) + 
    # Added to update enlarge the frame of the graph so the text is not cut
    geom_text(aes(x = xDodge-0.5, y = meanData, label = ""))
}

#SORT THE ARCHETYPES IN CLUSTERS BASED ON PRESENCE AND WINRATE
#' Title
#'
#' @param archetypeRankingDf the dataframe returned by archetype_ranking()
#' @param pieShare the value of the cut to be set in "Others" for an archetype.
#' @param presence the definition of metagame presence (aka share) to use. 
#' It can be:
#' - "Copies": the number of lines in the dataframe dedicated to that archetype
#' - "Players": the number of different players piloting that archetype
#' - "Matches": the number of matches played by the archetype
#' @param beginning the date to be displayed in the title as the beginning of 
#' the dataset
#' @param end the date to be displayed in the title as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param mtgFormat the format of the events in the data
#'
#' @return
#' @export
#'
#' @examples
winrate_and_presence_graph = function (archetypeRankingDf,pieShare,presence,
                                       beginning,end,eventType,mtgFormat){
  # Keep only the most present decks
  arch_most_played = archetypeRankingDf
  arch_most_played$Presence = 100 * unlist(arch_most_played[presence]) / 
    sum(unlist(arch_most_played[presence]))
  arch_most_played$MeasuredWinrate = 100 * arch_most_played$MeasuredWinrate
  presence_min = pieShare / 100 * sum(archetypeRankingDf[presence])
  arch_most_played = 
    arch_most_played[arch_most_played[presence] >= presence_min,]

  # arch_most_played$LabelRich = paste0("**",arch_most_played$Archetype,"**",
  #                                 "<br>Presence: ",
  #                                 round(arch_most_played$Presence, digits = 1)
  #                                 ,"%<br>Win rate: ",
  #                                 round(arch_most_played$MeasuredWinrate,
  #                                       digits = 1),"%")
  # 
  # arch_most_played$Label = paste0(arch_most_played$Archetype,
  #                                 "\nPresence: ",
  #                                 round(arch_most_played$Presence, digits = 1)
  #                                 ,"%\nWin rate: ",
  #                                 round(arch_most_played$MeasuredWinrate,
  #                                       digits = 1),"%")
  
  x_label = "Presence"
  y_label = "Winrate"
  graph_title=paste0("Win rates depending on presence (",presence,") of ",
                     mtgFormat, " archetypes\nbetween ", beginning, " and ",
                     end, " in ", eventType)
  graph_subtitle=paste("by Anaël Yahi")
  
  ggplot(arch_most_played, 
         aes(x = Presence, y = MeasuredWinrate, color = Archetype)) + 
    coord_cartesian() + scale_x_continuous(trans = 'log10') + 
    labs(x = x_label, y = y_label, title = graph_title, 
         subtitle = graph_subtitle) + 
    
    # geom_richtext(aes(label=LabelRich)) +
    # geom_label_repel(aes(label=Label)) +
    geom_label_repel(aes(label=Archetype)) +
    
    theme(axis.title.x = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
          axis.title.y = 
            element_text(margin = margin(t = 0, r = 20, b = 0, l = 0)),
          panel.background = element_blank(),
          axis.line.x=element_line(color="black"),
          axis.line.y=element_line(color="black"),
          axis.ticks.x = element_blank(),
          axis.ticks.y = element_blank(),
          text = element_text(size = 14),
          legend.position = "none") +
  geom_point(aes(size=Players))
}
