################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       06-Card_Data_Treatment.R                     #####
##### Use this file to import functions that will provide the classical    #####
##### Card analysis metrics.                                             #####
################################################################################

# # For development
# df = tournamentDf

#' Title
#'
#' @param df the dataframe generated by generate_df() 
#'
#' @return
#' @export
#'
#' @examples
get_card_data = function(df){
  
  # # For development only
  # df = tournamentDf
  
  Mainboards = lapply(df$Mainboard, function(MD){
    MD$CardName
  })
  
  Sideboards = sapply(df$Sideboard, function(SB){
    SB$CardName
  })
  
  MainboardCards = unique(unlist(Mainboards))
  SideboardCards = unique(unlist(Sideboards))
  
  CardData = data.frame(CardNames = c(MainboardCards,SideboardCards))
  
  CardDecklistsPresence = lapply(CardData$CardNames, function(CardName){
    MDPresence = sapply(Mainboards, function(MD, name) {name %in% MD}, CardName)
    SBPresence = sapply(Sideboards, function(SB, name) {name %in% SB}, CardName)
    DecklistsPresence = (MDPresence | SBPresence)
    return(DecklistsPresence)
  })
  names(CardDecklistsPresence) = CardData$CardNames
  
  CardData$Decklist.Count = 
    sapply(CardDecklistsPresence, function(presenceInDecklists){n
      sum(presenceInDecklists)
      })
  CardData$Decklist.Share = round(100 * CardData$Decklist.Count / nrow(df), 
                                 digits = 2)
  
  CardData$Wins = sapply(CardDecklistsPresence, function(cardPresenceInDecklist, df){
    dfCard = df[cardPresenceInDecklist,]
    return(sum(dfCard$Wins))
  },df)
  CardData$Losses = sapply(CardDecklistsPresence, function(cardPresenceInDecklist, df){
    dfCard = df[cardPresenceInDecklist,]
    return(sum(dfCard$Losses))
  },df)
  CardData$Draws = sapply(CardDecklistsPresence, function(cardPresenceInDecklist, df){
    dfCard = df[cardPresenceInDecklist,]
    return(sum(dfCard$Draws))
  },df)
  
  CardData = CardData[CardData$Wins + CardData$Losses > 0,]
  CardData$Matches = CardData$Wins + CardData$Losses + CardData$Draws
  CardData$Win.Rate.Without.Draws = round(100 * CardData$Wins / 
    (CardData$Wins + CardData$Losses), digits = 2)
  CardData$Win.Rate.With.Draws = round(100 * CardData$Wins / CardData$Matches, 
                                       digits = 2)
  CardData$Match.Share = round(100 * CardData$Matches / 
                                    sum(df$Wins + df$Losses + df$Draws), 
                                  digits = 2)
  
  CardData$Win.Rate.CI.95.Lower.Bound = mapply(FUN = function(wins, defeats){
    round(binom.test(wins, wins + defeats, p = 0.5, alternative = "two.sided", 
                     conf.level = 0.95)$conf.int[1] * 100, digits = 2)
  }, CardData$Wins, CardData$Losses)
  
  CardData$Win.Rate.CI.95.Upper.Bound =  mapply(FUN = function(wins, defeats){
    round(binom.test(wins, wins + defeats, p = 0.5, alternative = "two.sided", 
                     conf.level = 0.95)$conf.int[2] * 100, digits = 2)
  }, CardData$Wins, CardData$Losses)
  
  CardData = CardData[order(CardData$Win.Rate.Without.Draws, decreasing = TRUE),]
  
  CardData
}
