################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       06-Player_Data_Treatment.R                     #####
##### Use this file to import functions that will provide the classical    #####
##### player analysis metrics.                                             #####
################################################################################

# # For development
# df = tournamentDf

#' Title
#'
#' @param df the dataframe generated by generate_df() 
#'
#' @return
#' @export
#'
#' @examples
get_player_data = function(df){
  
  # # For development only
  # df = tournamentDf
  
  playerData = data.frame(Players = unique(df$Player))
  
  playerData$Wins = sapply(X = playerData$Players, 
                              FUN = function(player, df) {
                                sum(df[df$Player == player,]$Wins)
                              }, df)
  
  playerData$Defeats = sapply(X = playerData$Players, 
                              FUN = function(player, df) {
                                sum(df[df$Player == player,]$Losses)
                              }, df)
  
  playerData$Draws = sapply(X = playerData$Players, 
                              FUN = function(player, df) {
                                sum(df[df$Player == player,]$Draws)
                              }, df)
  
  playerData$Matches = playerData$Wins + playerData$Defeats + playerData$Draws
  
  # Remove players that appear in the JSON but don't have any recorded match
  playerData = playerData[playerData$Wins + playerData$Defeats >0,]
  
  playerData$Win.Rate = round(100 * playerData$Wins / 
                                (playerData$Wins + playerData$Defeats), 
                              digits = 2)
  
  
  playerData$Win.Rate.CI.Lower.Bound = mapply(FUN = function(wins, defeats){
    round(binom.test(wins, wins + defeats, p = 0.5, alternative = "two.sided", 
               conf.level = CIPercent)$conf.int[1] * 100, digits = 2)
  }, playerData$Wins, playerData$Defeats)
  
  playerData$Win.Rate.CI.Upper.Bound =  mapply(FUN = function(wins, defeats){
    round(binom.test(wins, wins + defeats, p = 0.5, alternative = "two.sided", 
               conf.level = CIPercent)$conf.int[2] * 100, digits = 2)
  }, playerData$Wins, playerData$Defeats)
  
  playerData$Number.of.Top32 = sapply(X = playerData$Players, 
                                     FUN = function(player, df) {
                                       dfPlayer = df[df$Player == player,]
                                       nrow(dfPlayer[dfPlayer$NumericResult<=32,])
                                     }, df)
  
  playerData$Number.of.Top8 = sapply(X = playerData$Players, 
                                     FUN = function(player, df) {
                                       dfPlayer = df[df$Player == player,]
                                       nrow(dfPlayer[dfPlayer$NumericResult<=8,])
                                     }, df)
  
  playerData$Number.of.Wins = sapply(X = playerData$Players, 
                                     FUN = function(player, df) {
                                       dfPlayer = df[df$Player == player,]
                                       nrow(dfPlayer[dfPlayer$NumericResult==1,])
                                     }, df)
  
  playerData = playerData[order(playerData$Win.Rate,decreasing=TRUE),]
  
  playerData
  
}
