################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                        99-Output_Export.R                            #####
##### Use this file to import functions that will save all the expected    #####
##### outputs in the right directories.                                    #####
################################################################################

library(xlsx)

#' Create the directories where to write the outputs
#'
#' @param resultDir the name of the general Result directory, presumably 
#' "Results/"
#' @param mtgFormat the format of the events in the data
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param csvResultDir the name of the final directory for CSV files, presumably
#' "CSV files"
#' @param pictureResultDir the name of the final directory for picture files, 
#' presumably "Picture files"
#' @param textResultDir the name of the final directory for text files, 
#' presumably "Text files"
#'
#' @return
#' @export
#'
#' @examples
createResultDirectories = function(resultDir,mtgFormat,beginning,end,eventType,
                                   csvResultDir,pictureResultDir,textResultDir){
  dir.create(file.path(resultDir,mtgFormat))
  dir.create(file.path(paste0(resultDir,mtgFormat,"/"), 
                       paste(beginning,end,sep="_")))
  dir.create(file.path(paste0(resultDir,mtgFormat,"/",
                              paste(beginning,end,sep="_")), eventType))
  
  pathToLastDirs = paste0(resultDir,mtgFormat,"/",
                          paste(beginning,end,sep="_"),"/",eventType,"/")
  dir.create(file.path(pathToLastDirs, csvResultDir))
  dir.create(file.path(pathToLastDirs, pictureResultDir))
  dir.create(file.path(pathToLastDirs, textResultDir))
  
  return(pathToLastDirs)
}

#' Title
#'
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param textResultDir the name of the final directory for text files, 
#' presumably "Text files" 
#'
#' @return
#' @export
#'
#' @examples
exportTextAnalysis = 
  function(df,pathToLastDirs,beginning,end,mtgFormat,eventType,chartShare,
           textResultDir){
    
  writingPath = paste0(pathToLastDirs,textResultDir)
  
  nDecks = nrow(df)
  nDiffPlayers = length(unique(df$Player))
  # nDiffCards = length(unique(c(MDStats$CardNames, SBStats$CardNames)))
  nArchetypes = length(unique(df$Archetype$Archetype))
  totNRounds = sum(df$NRounds) + sum(df$T8Matches)
  # avgNbRoundsWTop8 = as.numeric(format(round(
  #   (sum(df$NRounds)+sum(df$T8Matches))/length(df$AnchorUri),2), nsmall = 2))
  avgNRounds = as.numeric(format(round(sum(df$NRounds) / 
                                          length(df$AnchorUri),2),nsmall=2))
  minNRounds = min(df$NRounds)
  maxNRounds = max(df$NRounds)
  nEvents = length(unique(df$TournamentName))
  
  eventInfo=paste("QUICK ANALYSIS OF THE DATA", 
                  "\nFormat: ", mtgFormat,
                  "\nBeginning: ", beginning,
                  "\nEnd: ", end,
                  "\nType of MTGO events: ", eventType,
                  "\nNumber of decks in the data: ", nDecks,
                  "\nCut to be displayed: ", chartShare, "%",
                  "\nNumber of different players in the data: ", nDiffPlayers,
                  # "\nNumber of different cards in the data: ", nDiffCards,
                  "\nNumber of exact archetypes in the data: ", nArchetypes,
                  "\nNumber of rounds played in the data (with top8): ",
                  totNRounds,
                  # "\nAverage number of rounds in the data (with top8):",
                  # avgNbRoundsWTop8,
                  "\nAverage number of rounds in the data (w/o top8): ",
                  avgNRounds,
                  "\nMinimum number of rounds in the data (w/o top8): ",
                  minNRounds,
                  "\nMaximum number of rounds in the data (w/o top8): ",
                  maxNRounds,
                  "\nNumber of events in the data: ", nEvents,sep="")
  
  analysisName = paste0(beginning,'-',end,"_",mtgFormat,"-",eventType,
                        '_Quick_Analysis.txt')
  cat(eventInfo, file = paste0(writingPath, analysisName))
  
  # Export the list of covered events with their URL
  coveredEvents=setNames(data.frame(matrix(ncol=2, nrow=nEvents)), 
                         c("TournamentName", "URL"))
  coveredEvents$TournamentName=unique(df$TournamentName)
  for (i in 1:nEvents){
    coveredEvents$URL[i] = df[df$TournamentName == 
                                coveredEvents$TournamentName[i],]$AnchorUri[1]
    coveredEvents$URL[i]<-gsub("#.*","",coveredEvents$URL[i])
  }
  
  titleEventFile = paste("List of", mtgFormat, eventType,"between",beginning, 
                         "and", end, "\n")
  
  listName = paste0(beginning, '-', end, '_List_of_', mtgFormat, "_", eventType,
                    '.txt')
  cat(titleEventFile, file = paste0(writingPath, listName))
  
  write.table(coveredEvents, paste0(writingPath, listName), 
              append=TRUE, row.names = FALSE, col.names = FALSE, sep = " - ")
  }

exportAchetypeCardData = function(archetype, df){
  archetypeCardData = get_archetype_card_data(archetype, df)
  archetypeCardDataDirPath = paste0(PathToLastDirs, ArchetypeCardDataResultDir)
  archetypeCardDataFileName = paste0(Beginning,'_', End, ' - Card Data of ',
                                     archetype, " in ", MtgFormat, " ", 
                                     EventType)
  dir.create(file.path(archetypeCardDataDirPath))
  write.csv(archetypeCardData,
            paste0(archetypeCardDataDirPath, archetypeCardDataFileName,'.csv'), 
            row.names = FALSE)
  write.xlsx(archetypeCardData,
             paste0(archetypeCardDataDirPath, archetypeCardDataFileName,'.xlsx'), 
             row.names = FALSE)
}

exportPlayerData = 
  function(df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           playerDataResultDir){
  PlayerData = get_player_data(df)
  PlayerDataDirPath = paste0(pathToLastDirs, playerDataResultDir)
  PlayerDataFileName = paste0(beginning,'_', end, ' - Player Data in ', 
                              MtgFormat, ' ', mtgFormat, ' ', eventType)
  dir.create(file.path(PlayerDataDirPath))
  write.csv(PlayerData, paste0(PlayerDataDirPath, PlayerDataFileName,'.csv'), 
            row.names = FALSE)
  write.xlsx(PlayerData, paste0(PlayerDataDirPath, PlayerDataFileName,'.xlsx'), 
             row.names = FALSE)
}
