################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                        99-Output_Export.R                            #####
##### Use this file to import functions that will save all the expected    #####
##### outputs in the right directories.                                    #####
################################################################################

library(xlsx)
library(rjson)

#' Create the directories where to write the outputs
#'
#' @param resultDir the name of the general Result directory, presumably 
#' "Results/"
#' @param mtgFormat the format of the events in the data
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param csvResultDir the name of the final directory for CSV files, presumably
#' "CSV files"
#' @param pictureResultDir the name of the final directory for picture files, 
#' presumably "Picture files"
#' @param textResultDir the name of the final directory for text files, 
#' presumably "Text files"
#'
#' @return
#' @export
#'
#' @examples
createResultDirectories = function(resultDir,mtgFormat,beginning,end,eventType,
                                   csvResultDir,pictureResultDir,textResultDir){
  dir.create(file.path(resultDir,mtgFormat))
  dir.create(file.path(paste0(resultDir,mtgFormat,"/"), 
                       paste(beginning,end,sep="_")))
  dir.create(file.path(paste0(resultDir,mtgFormat,"/",
                              paste(beginning,end,sep="_")), eventType))
  
  pathToLastDirs = paste0(resultDir,mtgFormat,"/",
                          paste(beginning,end,sep="_"),"/",eventType,"/")
  dir.create(file.path(pathToLastDirs, csvResultDir))
  dir.create(file.path(pathToLastDirs, pictureResultDir))
  dir.create(file.path(pathToLastDirs, textResultDir))
  
  return(pathToLastDirs)
}

#' Write a textual analysis of the results, such as the formats, number of 
#' players, archetypes, matches, etc. And write another file with the links 
#' to all the events used in the analysis.
#'
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param textResultDir the name of the final directory for text files, 
#' presumably "Text files" 
#'
#' @return N/A
#' @export TXT Two txt files.
#'
#' @examples
exportTextAnalysis = 
  function(df,pathToLastDirs,beginning,end,mtgFormat,eventType,chartShare,
           textResultDir){
    
  writingPath = paste0(pathToLastDirs,textResultDir)
  
  nDecks = nrow(df)
  nDiffPlayers = length(unique(df$Player))
  # nDiffCards = length(unique(c(MDStats$CardNames, SBStats$CardNames)))
  nArchetypes = length(unique(df$Archetype$Archetype))
  totMatches = sum(df$Matches)
  # avgNbRoundsWTop8 = as.numeric(format(round(
  #   sum(df$Matches)/length(df$AnchorUri),2), nsmall = 2))
  avgMatches = as.numeric(format(round(sum(df$Matches) / 
                                          length(df$AnchorUri),2),nsmall=2))
  minMatches = min(df$Matches)
  maxMatches = max(df$Matches)
  nEvents = length(unique(df$TournamentName))
  
  eventInfo = paste("QUICK ANALYSIS OF THE DATA", 
                  "\nFormat: ", mtgFormat,
                  "\nBeginning: ", beginning,
                  "\nEnd: ", end,
                  "\nType of MTGO events: ", eventType,
                  "\nNumber of decks in the data: ", nDecks,
                  "\nCut to be displayed: ", chartShare, "%",
                  "\nNumber of different players in the data: ", nDiffPlayers,
                  # "\nNumber of different cards in the data: ", nDiffCards,
                  "\nNumber of exact archetypes in the data: ", nArchetypes,
                  "\nNumber of rounds played in the data (with top8): ",
                  totMatches,
                  # "\nAverage number of rounds in the data (with top8):",
                  # avgNbRoundsWTop8,
                  "\nAverage number of rounds in the data (w/o top8): ",
                  avgMatches,
                  "\nMinimum number of rounds in the data (w/o top8): ",
                  minMatches,
                  "\nMaximum number of rounds in the data (w/o top8): ",
                  maxMatches,
                  "\nNumber of events in the data: ", nEvents, sep="")
  
  analysisName = paste0(beginning,'-',end,"_",mtgFormat,"-",eventType,
                        '_Quick_Analysis.txt')
  cat(eventInfo, file = paste0(writingPath, analysisName))
  
  # Export the list of covered events with their URL
  coveredEvents = setNames(data.frame(matrix(ncol=2, nrow=nEvents)), 
                         c("TournamentName", "URL"))
  coveredEvents$TournamentName=unique(df$TournamentName)
  for (i in 1:nEvents){
    coveredEvents$URL[i] = df[df$TournamentName == 
                                coveredEvents$TournamentName[i],]$AnchorUri[1]
    coveredEvents$URL[i]<-gsub("#.*","",coveredEvents$URL[i])
  }
  
  titleEventFile = paste("List of", mtgFormat, eventType,"between",beginning, 
                         "and", end, "\n")
  
  listName = paste0(beginning, '-', end, '_List_of_', mtgFormat, "_", eventType,
                    '.txt')
  cat(titleEventFile, file = paste0(writingPath, listName))
  
  write.table(coveredEvents, paste0(writingPath, listName), 
              append=TRUE, row.names = FALSE, col.names = FALSE, sep = " - ")
}

#' Write a table in CSV and/or XLSX with the win rate, presence and top analysis
#' of all the players.
#'
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param playerDataResultDir the name of the final directory for text files, 
#' presumably "Player Data" 
#' @param writeCSV parameter to write a CSV file or not
#' @param writeXLSX parameter to write a XSLX file or not
#' @param writeJSON parameter to write a JSON file or not
#'
#' @return N/A
#' @export Table Up to one CSV and XLSX files with the player data
#'
#' @examples
exportPlayerData = 
  function(df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           playerDataResultDir,writeCSV,writeXLSX,writeJSON){
    # # For development only
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # playerDataResultDir = PlayerDataResultDir
    
  PlayerData = get_player_data(df)
  names(PlayerData) = gsub("\\.", "-", names(PlayerData))
  PlayerDataDirPath = paste0(pathToLastDirs, playerDataResultDir)
  PlayerDataFileName = paste0(beginning,'_', end, ' - Player Data in ', 
                              mtgFormat, ' ', eventType)
  dir.create(file.path(PlayerDataDirPath))
  if(writeCSV){
    write.csv(PlayerData, paste0(PlayerDataDirPath, PlayerDataFileName,'.csv'), 
              row.names = FALSE)
  }
  if(writeXLSX){
    write.xlsx(PlayerData, paste0(PlayerDataDirPath, PlayerDataFileName,'.xlsx'), 
               row.names = FALSE)
  }
  if(writeJSON){
    PlayerDataJSON = toJSON(PlayerData)
    write(PlayerDataJSON, paste0(PlayerDataDirPath, PlayerDataFileName,'.json'))
  }
}

#' Write a table in CSV and/or XLSX with the win rate and presence analysis
#' of all the cards
#'
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param cardDataResultDir the name of the final directory for text files, 
#' presumably "Card Data" 
#' @param writeCSV parameter to write a CSV file or not
#' @param writeXSLX parameter to write a XSLX file or not
#' @param writeJSON parameter to write a JSON file or not
#'
#' @return N/A
#' @export Table Up to one CSV and XLSX files with the card data
#'
#' @examples
exportCardData = 
  function(df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           cardDataResultDir,writeCSV,writeXLSX,writeJSON){
    # # For development only
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # cardDataResultDir = cardDataResultDir
    
    cardData = get_card_data(df)
    names(cardData) = gsub("\\.", "-", names(cardData))
    
    cardDataDirPath = paste0(pathToLastDirs, cardDataResultDir)
    cardDataFileName = paste0(beginning,'_', end, ' - Card Data in ', 
                                mtgFormat, ' ', eventType)
    dir.create(file.path(cardDataDirPath))
    if(writeCSV){
      write.csv(cardData, paste0(cardDataDirPath, cardDataFileName,'.csv'), 
                row.names = FALSE)
    }
    if(writeXLSX){
      write.xlsx(cardData, paste0(cardDataDirPath, cardDataFileName,'.xlsx'), 
                 row.names = FALSE)
    }
    if(writeJSON){
      cardDataJSON = toJSON(cardData)
      write(cardDataJSON, paste0(cardDataDirPath, cardDataFileName,'.json'))
    }
  }

#' Write a table in CSV and/or XLSX with the breakdown of the win rate and 
#' presence of all cards in the archetype.
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param archetypeCardDataResultDir the name of the final directory for text files, 
#' presumably "Archetype Card Data" 
#' @param writeCSV parameter to write a CSV file or not
#' @param writeXSLX parameter to write a XSLX file or not
#' @param writeJSON parameter to write a JSON file or not
#'
#' @return N/A
#' @export Table Up to one CSV and XLSX files with the archetype card data
#'
#' @examples
exportArchetypeCardData = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           archetypeCardDataResultDir,writeCSV,writeXLSX,writeJSON){
    # # For development only
    # archetypeName = "Rakdos Scam"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # archetypeCardDataResultDir = ArchetypeCardDataResultDir
    
    ArchetypeCardData = get_archetype_card_data(archetypeName, "All", df)
    names(ArchetypeCardData) = gsub("\\.", "-", names(ArchetypeCardData))
    ArchetypeCardDataDirPath = paste0(pathToLastDirs, archetypeCardDataResultDir)
    ArchetypeCardDataFileName = paste0(beginning,'_', end, ' - ', archetypeName,
                                       ' Card Data in ', mtgFormat, ' ', eventType)
    dir.create(file.path(ArchetypeCardDataDirPath))
    if(writeCSV){
      write.csv(as.matrix(ArchetypeCardData), 
                paste0(ArchetypeCardDataDirPath, 
                       ArchetypeCardDataFileName,'.csv'), 
                row.names = FALSE)
    }
    if(writeXLSX){
      write.xlsx(ArchetypeCardData, 
                 paste0(ArchetypeCardDataDirPath, 
                        ArchetypeCardDataFileName,'.xlsx'), 
                 row.names = FALSE)
    }
    if(writeJSON){
      ArchetypeCardDataJSON = toJSON(ArchetypeCardData)
      write(ArchetypeCardDataJSON, 
            paste0(ArchetypeCardDataDirPath, 
                   ArchetypeCardDataFileName,'.json'))
    }
    # return(ArchetypeCardData)
  }

#' Write a table in CSV and/or XLSX with the breakdown of the win rate and 
#' presence of all cards in the archetype. 
#' The details of the cards are broken down by the number of copies.
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param archetypeCardDataResultDir the name of the final directory for text files, 
#' presumably "Archetype Card Data" 
#' @param writeCSV parameter to write a CSV file or not
#' @param writeXSLX parameter to write a XSLX file or not
#' @param writeJSON parameter to write a JSON file or not
#'
#' @return N/A
#' @export Table Up to one CSV and XLSX files with the archetype card data
#'
#' @examples
exportArchetypeCardDataByCount = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           ArchetypeCardDataByCountResultDir,writeCSV,writeXLSX,writeJSON){
    # # For development only
    # archetypeName = "Rakdos Scam"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # ArchetypeCardDataByCountResultDir = ArchetypeCardDataByCountResultDir
    
    ArchetypeCardDataByCount = 
      get_archetype_card_data_by_count(archetypeName, "All", df)
    names(ArchetypeCardDataByCount) = 
      gsub("\\.", "-", names(ArchetypeCardDataByCount))
    ArchetypeCardDataByCountDirPath = 
      paste0(pathToLastDirs, ArchetypeCardDataByCountResultDir)
    ArchetypeCardDataByCountFileName = 
      paste0(beginning,'_', end, ' - ', archetypeName,' Card Data By Count in ', 
             mtgFormat, ' ', eventType)
    dir.create(file.path(ArchetypeCardDataByCountDirPath))
    if(writeCSV){
      write.csv(as.matrix(ArchetypeCardDataByCount), 
                paste0(ArchetypeCardDataByCountDirPath, 
                       ArchetypeCardDataByCountFileName,'.csv'), 
                row.names = FALSE)
    }
    if(writeXLSX){
      write.xlsx(ArchetypeCardDataByCount, 
                 paste0(ArchetypeCardDataByCountDirPath, 
                        ArchetypeCardDataByCountFileName,'.xlsx'), 
                 row.names = FALSE)
    }
    if(writeJSON){
      ArchetypeCardDataByCountJSON = toJSON(ArchetypeCardDataByCount)
      write(ArchetypeCardDataByCountJSON, 
            paste0(ArchetypeCardDataByCountDirPath, 
                   ArchetypeCardDataByCountFileName,'.json'))
    }
    # return(ArchetypeCardDataByCount)
  }

#' Write a text file with the average deck list for a given archetype in plain
#' text (theoretically copy-pastable in websites for visual view)
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param averageDeckListResultDir the name of the final directory for text files, 
#' presumably "Average Deck Lists" 
#'
#' @return N/A
#' @export TXT A text file with the average deck list in plain text
#'
#' @examples
exportAverageDeckList = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           averageDeckListResultDir){
    # # For development only
    # archetypeName = "Rakdos Midrange"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # averageDeckListResultDir = AverageDeckListResultDir

    averageDeckListData = get_average_decklist(
      archetypeName, get_archetype_most_common_colors(archetypeName, df)[1], df)
    
   MainDeckText = paste(averageDeckListData$MainDeck$CardCountMD, 
          averageDeckListData$MainDeck$CardNamesMD, collapse = "\n")
   SideBoardText = paste(averageDeckListData$SideBoard$CardCountSB, 
                         averageDeckListData$SideBoard$CardNamesSB, collapse = "\n")
   
   AverageDeckListText = paste(MainDeckText, SideBoardText, sep = "\n\n")
   
   AverageDeckListDirPath = paste0(pathToLastDirs,averageDeckListResultDir)
   dir.create(file.path(AverageDeckListDirPath))
   
   AverageDeckListFileName = paste0(beginning,'_', end, ' - ', archetypeName,
                                    ' - Average Deck List in ', mtgFormat, ' ', 
                                    eventType, '.txt')
   cat(AverageDeckListText, 
       file = paste0(AverageDeckListDirPath, AverageDeckListFileName))
    
    # return(averageDeckListData)
  }

#' Write a text file with the optimized deck list for a given archetype in plain
#' text (theoretically copy-pastable in websites for visual view)
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param optimizedDeckListResultDir the name of the final directory for text files, 
#' presumably "Optimized Deck Lists" 
#'
#' @return N/A
#' @export TXT A text file with the optimized deck list in plain text
#'
#' @examples
exportOptimizedDeckList = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           optimizedDeckListResultDir){
    # # For development only
    # archetypeName = "Rakdos Midrange"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # optimizedDeckListResultDir = OptimizedDeckListResultDir
    
    optimizedDeckListData = get_winrate_optimized_decklist(
      archetypeName, get_archetype_most_common_colors(archetypeName, df)[1], df)
    
    OptimizedDeckListText = paste(
      paste(optimizedDeckListData$MainDeck$Card.Count.and.Name.MD, 
            collapse = "\n"), 
      paste(optimizedDeckListData$SideBoard$Card.Count.and.Name.SB, 
            collapse = "\n"), 
      sep = "\n\n")
    
    OptimizedDeckListDirPath = paste0(pathToLastDirs,optimizedDeckListResultDir)
    dir.create(file.path(OptimizedDeckListDirPath))
    
    OptimizedDeckListFileName = paste0(beginning,'_', end, ' - ', archetypeName,
                                     ' - Optimized Deck List in ', mtgFormat, ' ', 
                                     eventType, '.txt')
    cat(OptimizedDeckListText, 
        file = paste0(OptimizedDeckListDirPath, OptimizedDeckListFileName))
    
    # return(optimizedDeckListData)
  }

#' Write a text file with the URL of the deck list for a given archetype that 
#' had the "best" performance in the data (highest wins - losses score, as 
#' defined by Frank Karsten).
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param bestDeckResultDir the name of the final directory for text files, 
#' presumably "Best Deck URL" 
#'
#' @return N/A
#' @export TXT A text file with the URL of the "best" deck list in plain text
#' for a given archetype
#'
#' @examples
exportBestDeck = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           bestDeckResultDir){
    # # For development only
    # archetypeName = "Rakdos Midrange"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # bestDeckResultDir = BestDeckResultDir
    
    bestDeckData = getBestDeck(archetypeName, df)
    
    bestDeckListText = paste(bestDeckData, collapse = "\n")
    
    bestDeckResultDirPath = paste0(pathToLastDirs,bestDeckResultDir)
    dir.create(file.path(bestDeckResultDirPath))
    
    bestDeckFileName = paste0(beginning,'_', end, ' - ', archetypeName,
                                       ' - Best Deck in ', mtgFormat, ' ', 
                                       eventType, '.txt')
    cat(bestDeckListText, 
        file = paste0(bestDeckResultDirPath, bestDeckFileName))
    
    # return(bestDeckData)
  }

#' Write a text file with the URL of the deck list for a given archetype that 
#' had the "best" performance in the data (highest wins - losses score, as 
#' defined by Frank Karsten).
#' 
#' @param df the dataframe returned by generate_df() 
#' @param pathToLastDirs the path returned by createResultDirectories(),
#' where to write the current outputs in final directories
#' @param beginning the date to be displayed in the path as the beginning of 
#' the dataset
#' @param end the date to be displayed in the path as the end of the dataset
#' @param mtgFormat the format of the events in the data
#' @param eventType the category of events to keep in the data. It can be:
#' Event type:
#' All sources = Everything (except MTGO Leagues - for any filter)
#' All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
#' Full Meta Events = Only events with the full metagame available
#' (not MTGO Official results)
#' ManaTraders = ManaTraders Series results
#' Paper Events Full Meta = Full esults from MTG Melee
#' Paper Events Top32 = Results of the top32 from MTG Melee
#' MTGO Official Competitions = Results from the MTGO website
#' MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
#' MTGO Preliminaries = As per name
#' @param chartShare the value of the cut to be set in "Others" for an archetype.
#' It must be a numeric value. For a cut at 2%, use chartShare=2 (not 0.02).
#' @param bestDeckResultDir the name of the final directory for text files, 
#' presumably "All Deck URL" 
#'
#' @return N/A
#' @export TXT A text file with the URL of the all the deck lists in plain text
#' for a given archetype
#'
#' @examples
exportAllDeckURL = 
  function(archetypeName,df,pathToLastDirs,beginning,end,mtgFormat,eventType,
           allDeckURLResultDir){
    # # For development only
    # archetypeName = "Rakdos Midrange"
    # df = tournamentDf
    # pathToLastDirs = PathToLastDirs
    # beginning = Beginning
    # end = End
    # mtgFormat = MtgFormat
    # eventType = EventType
    # allDeckURLResultDir = AllDeckURLResultDir
    
    allDeckURLData = getURLofDeck(archetypeName, df)
    
    allDeckURLListText = paste(allDeckURLData, collapse = "\n")
    
    allDeckURLResultDirPath = paste0(pathToLastDirs,allDeckURLResultDir)
    dir.create(file.path(allDeckURLResultDirPath))
    
    allDeckURLFileName = paste0(beginning,'_', end, ' - ', archetypeName,
                              ' - All Decks in ', mtgFormat, ' ', 
                              eventType, '.txt')
    cat(allDeckURLListText, 
        file = paste0(allDeckURLResultDirPath, allDeckURLFileName))
    
    # return(allDeckURLData)
  }
