################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       01-Parameters.R                                #####
##### Use this file to tune the outputs of the code by selecting which     #####
##### features to run and on which type of data                            #####
################################################################################

# Names of the main directories in the project
DataDir = "Data/"
ResultDir = "Results/"

# Format of the wanted events
# # Leave this vector untouched if used, to avoid typing mistakes
# MTGFormats = c("Sealed","Standard","Pioneer","Modern","Pauper","Legacy",
#                "Vintage","All Formats")
# MTGFormat = MTGFormats[4]

MTGFormat = "Modern"

# Name of the tournament result data source file for the corresponding format
# Currently automatically updated based on the format name
TournamentResultFile = paste0(DataDir,MTGFormat,"_data.json")

#Earliest date - if NA, starts from the beginning of the data
Beginning="2022-11-15"

#Latest date - if NA, goes up to the end of the data
End="2023-03-20"

# Event type:
# All sources = Everything (except MTGO Leagues - for any filter)
# All Events Top32 = Only events with a top32 (aka not MTGO Preliminaries)
# Full Meta Events = Only events with the full metagame available 
# (not MTGO Official results)
# ManaTraders = ManaTraders Series results
# Paper Events Full Meta = Full esults from MTG Melee
# Paper Events Top32 = Results of the top32 from MTG Melee
# MTGO Official Competitions = Results from the MTGO website
# MTGO Events Top32 = MTGO results with a top32 (so not Preliminaries)
# MTGO Preliminaries = As per name

# Leave this vector untouched if used, to avoid typing mistakes
EventTypes = c("All sources",
               "All Events Top32",
               "Full Meta Events",
               "ManaTraders", 
               "Paper Events Full Meta",
               "Paper Events Top32",
               "MTGO Official Competitions", 
               "MTGO Events Top32",
               "MTGO Preliminaries")

EventType = EventTypes[3]

#Required metagame share to appear on pie chart (gets converted to % later)
PieShare=2
#Automatically update this value with the average presence if TRUE
PieShare.autoupdate=T

#Required metagame share to appear on histogram (gets converted to % later)
HistShare=2
#Automatically update this value with the average presence if TRUE
HistShare.autoupdate=T