################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       _getter_Runner.R                               #####
##### Use this file to manually run some simple getters on the data        #####
################################################################################

# Set the working directory as the current R project directory 
# Mostly useful because the code keeps changing directories to write graphs
# Maybe it can do it otherwise and more efficiently?
library(rprojroot)
library(knitr)
setwd(find_rstudio_root_file())

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = paste0(find_rstudio_root_file(),"/Scripts/")
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"02-Simple_Getters.R")))
source(file.path(paste0(functionScriptDir,"03-Metagame_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"04-Metagame_Graph_Generation.R")))
source(file.path(paste0(functionScriptDir,"05-Decklist_Analysis.R")))
source(file.path(paste0(functionScriptDir,"06-Player_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"07-Card_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

PathToLastDirs = 
  createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                          CsvResultDir, PictureResultDir, TextResultDir)

#Import raw data
RawData = fromJSON(TournamentResultFile)[[1]]
tournamentDf = generate_df(
  RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End)

############################   Compute analysis   ############################## 

# Get the following columns: 
# Archetype Copies Players Matches MeasuredWinrate CILowerBound CIUpperBound
archetypeMetricsDf = archetype_metrics(tournamentDf)

# Update the cut value based on the data. If too small, set at 1% for graph
# readability.
if(Share.autoupdate){
  StatShare = 
    round(mean(unlist(archetypeMetricsDf[Presence])) / 
            sum(unlist(archetypeMetricsDf[Presence])) * 100, digits = 2)
  ChartShare = max(StatShare, 1)
}else {
  StatShare = ChartShare
}

# Add the following columns:
# NormalizedPresence NormalizedMeasuredWinrate NormalizedSum Rank
archetypeRankingDf = archetype_ranking(archetypeMetricsDf, Presence)
# Keep only the most played decks and add some columns:
# Presence Tiers
archetypeTiersDf = archetype_tiers(archetypeRankingDf, Presence, StatShare)
# Get the required data to build the matchup matrix of the most present
# archetypes
muMatrixData = generate_matchup_data(tournamentDf, ChartShare, Presence)

exportTextAnalysis(tournamentDf, PathToLastDirs, Beginning, End, MtgFormat, 
                   EventType, ChartShare,TextResultDir)

############################################################ 

cardName = "Counterspell"
archetypeName = "Dimir Shadow"
archetypeName2 = "Hammer Time"

addArchetypeColor = T
if(addArchetypeColor){
  tournamentDf$Archetype$Archetype = 
    mapply(function(archetypeName, archetypeColor) {
      ifelse(archetypeName %in% c("Footfalls"),
             paste(archetypeColor, archetypeName),
             archetypeName
      )
    }, tournamentDf$Archetype$Archetype, tournamentDf$Archetype$Color)
}

removeArchetypeColor = T
if(removeArchetypeColor){
  tournamentDf[grep(pattern = "Humans", x = tournamentDf$Archetype$Archetype),]$
    Archetype$Archetype = "Humans"
}

splitArchetypeByCard = T
if(splitArchetypeByCard){
  tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]$Archetype$Archetype =
    ifelse(sapply(tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]$Allboards, 
                  function(boards){cardName %in% boards$CardName}),
           paste0(archetypeName," (with ",cardName,")"),
           paste0(archetypeName," (without ",cardName,")"))
  
  archetypeWithCardDF = tournamentDf[tournamentDf$Archetype$Archetype == 
                                       paste0(archetypeName," (with ",cardName,")"),]
  archetypeWithoutCardDF = tournamentDf[tournamentDf$Archetype$Archetype == 
                                       paste0(archetypeName," (without ",cardName,")"),]
  print(paste("The win rate of", archetypeName, "decks with", cardName, "is",
              round(100*sum(archetypeWithCardDF$NWins)/
                      (sum(archetypeWithCardDF$NWins) + 
                         sum(archetypeWithCardDF$Losses)),digits = 2),"%.",
              nrow(archetypeWithCardDF),"decks played it."))
  print(paste("The win rate of", archetypeName, "decks without", cardName, "is",
              round(100*sum(archetypeWithoutCardDF$NWins)/
                      (sum(archetypeWithoutCardDF$NWins) + 
                         sum(archetypeWithoutCardDF$Losses)),digits = 2),"%.",
              nrow(archetypeWithoutCardDF),"decks played it."))
  
  # Get the required data to build the matchup matrix of a single archetype
  muMatrixDataArchetypeWithCard = generate_matchup_data(tournamentDf, ChartShare, 
                                                Presence, paste0(archetypeName," (with ",cardName,")"))
  # Get the required data to build the matchup matrix of a single archetype
  muMatrixDataArchetypeWithoutCard = generate_matchup_data(tournamentDf, ChartShare, 
                                                        Presence, paste0(archetypeName," (without ",cardName,")"))
  # Draw the corresponding matchup matrix
  generate_matchup_matrix(muMatrixDataArchetypeWithCard, ChartShare, Presence, 
                          Beginning, End, MtgFormat, EventType)
  # Draw the corresponding matchup matrix
  generate_matchup_matrix(muMatrixDataArchetypeWithoutCard, ChartShare, Presence, 
                          Beginning, End, MtgFormat, EventType)
}

archetypeDfWithCardInSB = tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]
archetypeDfWithCardInSB = archetypeDfWithCardInSB[sapply(archetypeDfWithCardInSB$Sideboard, 
       function(sideboard){cardName %in% sideboard$CardName}),]
archetypeDfWithCardInSB$AnchorUri

mergeUWX = T
if(mergeUWX){
  archetypeName = "UWx Control"
  
  tournamentDf$Archetype$Archetype = 
    mapply(function(archArch) {
      ifelse(archArch %in% c("Azorius Control","Jeskai Control",
                                  "Bant Control","Esper Control"),
             archetypeName ,
             archArch
      )
    }, tournamentDf$Archetype$Archetype)
  
  tournamentDf$Matchups = 
    mapply(function(MU){
      MU$OpponentArchetype = mapply(function(oppArch) {
        ifelse(oppArch %in% c("Azorius Control","Jeskai Control",
                               "Bant Control","Esper Control"),
               archetypeName ,
               oppArch
        )
      }, MU$OpponentArchetype)
      return(MU)
    },tournamentDf$Matchups)
}

archetypeName = "WURG Control"
optimizedColorData = get_archetype_data_by_color(archetypeName,tournamentDf)
optimizedColorData
optimizedColor = optimizedColorData$Colors[1]
# optimizedColor = "URG"
get_winrate_optimized_decklist(archetypeName,optimizedColor,tournamentDf)

getConflictURL(tournamentDf)
getConflictArchetype(tournamentDf)
getUnknown(tournamentDf)
# getURLofCard(cardName, tournamentDf)
getURLofDeck(archetypeName, tournamentDf)
getBestDeck(archetypeName, tournamentDf)
get_matchup_data(tournamentDf, archetypeName, archetypeName2)

muMatrixData = generate_matchup_data(tournamentDf, ChartShare, Presence)
write.xlsx(muMatrixData,
           paste0(Beginning,"_",End,"_",MtgFormat,"_",EventType,"_","MU Matrix",'.xlsx'), 
           row.names = FALSE)

# Get the required data to build the matchup matrix of a single archetype
muMatrixDataArchetype = generate_matchup_data(tournamentDf, ChartShare, 
                                              Presence, archetypeName)
# Draw the corresponding matchup matrix
generate_matchup_matrix(muMatrixDataArchetype, ChartShare, Presence, Beginning, 
                        End, MtgFormat, EventType)

getArchetypeWinRate = function(tournamentDf, archetypeName){
  archetypeDf = tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]
  archetypePresence = paste0(round(nrow(archetypeDf)/nrow(tournamentDf),
                                   digits=4)*100,"%")
  archetypeWinRateWDraws = paste0(round(sum(archetypeDf$NWins)/
                                          sum(archetypeDf$Matches),
                                        digits=4)*100,"%")
  archetypeWinRateWoDraws = paste0(round(sum(archetypeDf$NWins)/
    (sum(archetypeDf$NWins) + sum(archetypeDf$Losses)),
    digits=4)*100,"%")
  archetypeDrawPercentage = paste0(round(sum(archetypeDf$Draws)/
                                           sum(archetypeDf$Matches),
                                         digits=4)*100,"%")
  
  colLabels = c("Archetype Name","Archetype Presence",
                "Archetype Win Rate w Draws", "Archetype Win Rate w/o Draws",
                "Archetype Draw Percentage")
  
  archetypeData = c(archetypeName, archetypePresence, archetypeWinRateWDraws,
                    archetypeWinRateWoDraws, archetypeDrawPercentage)
  archetypeDF = t(data.frame(archetypeData))
  rownames(archetypeDF) = c()
  colnames(archetypeDF) = colLabels
  
  print(kable(archetypeDF))
}
getArchetypeWinRate(tournamentDf, archetypeName)

getArchetypeWR = function(tournamentDf, archetypeName){
  archetypeDf = tournamentDf[tournamentDf$Archetype$Archetype == archetypeName,]
  paste("The win rate (w/o draws) of",archetypeName,"is:",
        round(100 * sum(archetypeDf$Wins)/(sum(archetypeDf$Wins) + sum(archetypeDf$Losses)),digits = 2),"%.")
}
archetypeName = "Bant Spirits"
getArchetypeWR(tournamentDf, archetypeName)
archetypeName = "Azorius Spirits"
getArchetypeWR(tournamentDf, archetypeName)

get_archetype_card_data(archetypeName, "W", tournamentDf)

getMainboardCardData = function(cardNames, tournamentDf, CIPercent, 
                                EventType, MtgFormat, Beginning, End){
  
  cardsData = lapply(cardNames, function(cardName, tournamentDf, CIPercent, 
                                         EventType, MtgFormat, Beginning, End){
    print(cardName)
    conditionCardPresence = sapply(tournamentDf$Mainboard, function(mainboard) {
      cardName %in% mainboard$CardName
    } )
    cardNMatches = sum(cardDf$Matches)
    cardPresence = paste0(round(sum(conditionCardPresence)/
                                  length(conditionCardPresence),digits=4)*100,"%")
    cardDf = tournamentDf[conditionCardPresence,]
    cardWinRateWoDraws = paste0(round(sum(cardDf$NWins)/
                                        (sum(cardDf$NWins+cardDf$Losses)),
                                      digits=4)*100,"%")
    lowerBoundWinRateWoDraws = 
      paste0(round(binom.test(sum(cardDf$NWins),
                              sum(cardDf$NWins+cardDf$Losses), 
                              p=0.5,alternative="two.sided", 
                              conf.level=CIPercent)$conf.int[1], digits=4)*100,"%")
    higherBoundWinRateWoDraws = 
      paste0(round(binom.test(sum(cardDf$NWins), sum(cardDf$NWins+cardDf$Losses),
                              p=0.5,alternative="two.sided", 
                              conf.level=CIPercent)$conf.int[2], digits=4)*100,"%")
    cardWinRateWDraws = paste0(round(sum(cardDf$NWins)/sum(cardDf$Matches),
                                     digits=4)*100,"%")
    lowerBoundWinRateWDraws = 
      paste0(round(binom.test(sum(cardDf$NWins), sum(cardDf$Matches), 
                              p=0.5,alternative="two.sided",
                              conf.level=CIPercent)$conf.int[1],
                   digits=4)*100,"%")
    higherBoundWinRateWDraws = 
      paste0(round(binom.test(sum(cardDf$NWins),
                              sum(cardDf$Matches),p=0.5,alternative="two.sided", 
                              conf.level=CIPercent)$conf.int[2], digits=4)*100,"%")
    cardDrawsPercentage = paste0(round(sum(cardDf$Draws)/sum(cardDf$Matches),
                                       digits=4)*100,"%")
    
    rowData = c(cardName,EventType,MtgFormat,Beginning,End,
                cardNMatches, cardPresence,
                cardWinRateWoDraws,lowerBoundWinRateWoDraws, 
                higherBoundWinRateWoDraws, cardWinRateWDraws,
                lowerBoundWinRateWDraws, 
                higherBoundWinRateWDraws,cardDrawsPercentage)
    
    return(rowData)
  }, tournamentDf, CIPercent, EventType, MtgFormat, Beginning, End)
  
  rowLabels = c("Card Name","Event Type","Format","Beginning Date","End Date",
                "Number of matches", "Card Presence","Card Win Rate Without Draws",
                paste0("Lower Bound of the ",CIPercent*100, 
                       "% CI w/o Draws"),
                paste0("Upper Bound of the ",CIPercent*100, 
                       "% CI w/o Draws"),
                "Card Win Rate With Draws",
                paste0("Lower Bound of the ",CIPercent*100, 
                       "% CI w Draws"),
                paste0("Upper Bound of the ",CIPercent*100, 
                       "% CI w Draws"),
                "Card Draw Percentage")
  
  cardsDF = data.frame(cardsData)
  colnames(cardsDF) = c()
  rownames(cardsDF) = rowLabels
  
  print(kable(cardsDF))
  return(cardsDF)
}



getMainboardCardData(cardNames, tournamentDf, CIPercent, 
                     EventType, MtgFormat, Beginning, End)

allboardCardData = function(cardNames, tournamentDf){
  
  cardsData = lapply(cardNames, function(cardName, tournamentDf){

    conditionCardPresenceAllboard = sapply(tournamentDf$Allboard, function(Allboard) {
      cardName %in% Allboard$CardName
    } )
    cardPresence = paste0(round(sum(conditionCardPresenceAllboard)/
                                  length(conditionCardPresenceAllboard),digits=4)*100,"%")
    
    conditionCardPresenceMainboard = sapply(tournamentDf$Mainboard, function(Mainboard) {
      cardName %in% Mainboard$CardName
    } )
    cardPresenceMainboard = paste0(round(sum(conditionCardPresenceMainboard)/
                                  length(conditionCardPresenceMainboard),digits=4)*100,"%")
    
    conditionCardPresenceSideboard = sapply(tournamentDf$Sideboard, function(Sideboard) {
      cardName %in% Sideboard$CardName
    } )
    cardPresenceSideboard = paste0(round(sum(conditionCardPresenceSideboard)/
                                  length(conditionCardPresenceSideboard),digits=4)*100,"%")
    
    cardDfAllboard = tournamentDf[conditionCardPresenceAllboard,]
    cardWinRateWoDrawsAllboard = paste0(round(sum(cardDfAllboard$NWins)/
                                        (sum(cardDfAllboard$NWins+cardDfAllboard$Losses)),
                                      digits=4)*100,"%")
    cardWinRateWDrawsAllboard = paste0(round(sum(cardDfAllboard$NWins)/sum(cardDfAllboard$Matches),
                                     digits=4)*100,"%")
    cardDrawsPercentageAllboard = paste0(round(sum(cardDfAllboard$Draws)/sum(cardDfAllboard$Matches),
                                       digits=4)*100,"%")
    
    cardDfMainboard = tournamentDf[conditionCardPresenceMainboard,]
    cardWinRateWoDrawsMainboard = paste0(round(sum(cardDfMainboard$NWins)/
                                                (sum(cardDfMainboard$NWins+cardDfMainboard$Losses)),
                                              digits=4)*100,"%")
    cardWinRateWDrawsMainboard = paste0(round(sum(cardDfMainboard$NWins)/sum(cardDfMainboard$Matches),
                                             digits=4)*100,"%")
    cardDrawsPercentageMainboard = paste0(round(sum(cardDfMainboard$Draws)/sum(cardDfMainboard$Matches),
                                               digits=4)*100,"%")
    
    
    cardDfSideboard = tournamentDf[conditionCardPresenceSideboard,]
    cardWinRateWoDrawsSideboard = paste0(round(sum(cardDfSideboard$NWins)/
                                                 (sum(cardDfSideboard$NWins+cardDfSideboard$Losses)),
                                               digits=4)*100,"%")
    cardWinRateWDrawsSideboard = paste0(round(sum(cardDfSideboard$NWins)/sum(cardDfSideboard$Matches),
                                              digits=4)*100,"%")
    cardDrawsPercentageSideboard = paste0(round(sum(cardDfSideboard$Draws)/sum(cardDfSideboard$Matches),
                                                digits=4)*100,"%")
    
    rowData = c(cardName,cardPresence,cardPresenceMainboard,cardPresenceSideboard,
                cardWinRateWoDrawsAllboard,cardWinRateWDrawsAllboard,cardDrawsPercentageAllboard,
                cardWinRateWoDrawsMainboard,cardWinRateWDrawsMainboard,cardDrawsPercentageMainboard,
                cardWinRateWoDrawsSideboard,cardWinRateWDrawsSideboard,cardDrawsPercentageSideboard
                )
    
    return(rowData)
  }, tournamentDf)
  
  colLabels = c("Card Name",
                "Card Presence (All boards)", "Presence (Mainboard)", "Presence (Sideboard)", 
                "Card Win Rate w/o Draws (All boards)", 
                "Card Win Rate with Draws (All boards)", 
                "Card Draw Percentage (All boards)", 
                "Card Win Rate w/o Draws (Mainboard)", 
                "Card Win Rate with Draws (Mainboard)", 
                "Card Draw Percentage (Mainboard)", 
                "Card Win Rate w/o Draws (Sideboard)", 
                "Card Win Rate with Draws (Sideboard)", 
                "Card Draw Percentage (Sideboard)")
  
  cardsDF = t(data.frame(cardsData))
  rownames(cardsDF) = c()
  colnames(cardsDF) = colLabels
  
  print(kable(cardsDF))
  View(cardsDF)
  return(cardsDF)
}

mainBoardCardData = function(cardNames, tournamentDf){
  
  cardsData = lapply(cardNames, function(cardName, tournamentDf){
    
    conditionCardPresenceMainboard = sapply(tournamentDf$Mainboard, function(Mainboard) {
      cardName %in% Mainboard$CardName
    } )
    cardPresenceMainboard = paste0(round(sum(conditionCardPresenceMainboard)/
                                           length(conditionCardPresenceMainboard),digits=4)*100,"%")
    
    cardDfMainboard = tournamentDf[conditionCardPresenceMainboard,]
    
    cardWinsMainboard = sum(cardDfMainboard$NWins)
    cardDefeatsMainboard = sum(cardDfMainboard$Losses)
    cardDrawsMainboard = sum(cardDfMainboard$Draws)
    cardRoundsMainboard = sum(cardDfMainboard$Matches)
    cardWinRateWoDrawsMainboard = paste0(round(cardWinsMainboard/
                                                 (cardWinsMainboard+cardDefeatsMainboard),
                                               digits=4)*100,"%")
    cardWinRateWDrawsMainboard = paste0(round(cardWinsMainboard/cardRoundsMainboard,
                                              digits=4)*100,"%")
    cardDrawsPercentageMainboard = paste0(round(cardDrawsMainboard/cardRoundsMainboard,
                                                digits=4)*100,"%")
    
    rowData = c(cardName,cardPresenceMainboard,
                cardWinsMainboard,
                cardDefeatsMainboard,
                cardDrawsMainboard,
                cardRoundsMainboard,
                cardWinRateWoDrawsMainboard,
                cardWinRateWDrawsMainboard,
                cardDrawsPercentageMainboard
    )
    
    return(rowData)
  }, tournamentDf)
  
  colLabels = c("Card Name", "Presence (Mainboard)",
                "Number of wins of the card (Mainboard)",
                "Number of defeats of the card (Mainboard)",
                "Number of draws of the card (Mainboard)",
                "Number of matches of the card (Mainboard): Wins+Defeats+Draws",
                "Card Win Rate w/o Draws (Mainboard): Wins/(Wins+Defeats)", 
                "Card Win Rate with Draws (Mainboard): Wins/Matches", 
                "Card Draw Percentage (Mainboard): Draws/Matchs")
  
  cardsDF = t(data.frame(cardsData))
  rownames(cardsDF) = c()
  colnames(cardsDF) = colLabels
  
  print(kable(cardsDF))
  View(cardsDF)
  return(cardsDF)
}


conditionCardPresenceAllboard = sapply(tournamentDf$Allboard, function(Allboard) {
  cardName %in% Allboard$CardName
} )

conditionCardPresenceMainboard = sapply(tournamentDf$Mainboard, function(Mainboard) {
  cardName %in% Mainboard$CardName
} )

conditionCardPresenceSideboard = sapply(tournamentDf$Sideboard, function(Sideboard) {
  cardName %in% Sideboard$CardName
} )

cardDfNotMainboard = tournamentDf[(!conditionCardPresenceMainboard),]
conditionCardPresenceSideboardNotMainboard = sapply(cardDfNotMainboard$Sideboard, function(Sideboard) {
  cardName %in% Sideboard$CardName
} )
cardDfSideboardNotMainboard = cardDfNotMainboard[conditionCardPresenceSideboardNotMainboard,]

cardDf = tournamentDf[conditionCardPresenceAllboard,]
sum(cardDf$NWins)
sum(cardDf$Losses)
cardWinRateWoDraws = paste0(round(sum(cardDf$NWins)/
                                    (sum(cardDf$NWins+cardDf$Losses)),
                                  digits=4)*100,"%")

cardNames = sort(c("The One Ring",
                   "Orcish Bowmasters",
                   "Fury",
                   "Chalice of the Void",
                   "Thoughtseize",
                   "Force of Negation",
                   "Boseiju, Who Endures",
                   "Endurance",
                   "Subtlety",
                   "Ragavan, Nimble Pilferer",
                   "Grief",
                   "Leyline Binding",
                   "Lightning Bolt",
                   "Lórien Revealed"
))
cardNames = "The One Ring"
allboardCardData(cardNames, tournamentDf)
mainBoardCardData(cardNames, tournamentDf)

MonoBlackDf = tournamentDf[tournamentDf$Archetype$Color == "B",]
MonoBlackDf$Archetype

conditionCardPresenceAllboard = sapply(tournamentDf$Allboard, function(Allboard) {
  cardNames %in% Allboard$CardName
} )
tournamentDf[conditionCardPresenceAllboard,]$AnchorUri

tournamentDf = updateDfForPT(tournamentDf)

# Normal Winrate
hist(archetypeRankingDf$MeasuredWinrate,breaks = 20)
shapiro.test(archetypeRankingDf$MeasuredWinrate)
ks.test(archetypeRankingDf$MeasuredWinrate, "pnorm")
library(fitdistrplus)
summary(fitdist(archetypeRankingDf[archetypeRankingDf$MeasuredWinrate>0,]$MeasuredWinrate/100, 
                distr = "beta", method = "mle"))
library(goft)
lnorm_test(archetypeRankingDf[archetypeRankingDf$MeasuredWinrate>0,]$MeasuredWinrate)
gamma_test(archetypeRankingDf[archetypeRankingDf$MeasuredWinrate>0,]$MeasuredWinrate)
weibull_test(archetypeRankingDf[archetypeRankingDf$MeasuredWinrate>0,]$MeasuredWinrate)
normal_test(archetypeRankingDf[archetypeRankingDf$MeasuredWinrate>0,]$MeasuredWinrate)
# Exponential presence
hist(archetypeRankingDf$Matches,breaks = 20)
ks.test(archetypeRankingDf$Matches, "pexp")
# Winrate and presence correlation
cor.test(archetypeRankingDf$MeasuredWinrate, 
         archetypeRankingDf$Matches/max(archetypeRankingDf$Matches),
         method = "pearson")
regWRPres = lm(MeasuredWinrate ~ Matches, data = archetypeRankingDf)
summary(regWRPres)
nrow(archetypeRankingDf)
# Normal normalized sum
hist(archetypeRankingDf$NormalizedSum,breaks = 20)
shapiro.test(archetypeRankingDf$NormalizedSum)
ks.test(archetypeRankingDf$NormalizedSum, "pnorm")
normal_test(archetypeRankingDf[archetypeRankingDf$NormalizedSum>0,]$NormalizedSum)


archetypeRankingDfAboveMean = 
  archetypeRankingDf[archetypeRankingDf$Matches 
                     >= mean(archetypeRankingDf$Matches),]

# Normal Winrate
hist(archetypeRankingDfAboveMean$MeasuredWinrate)
shapiro.test(archetypeRankingDfAboveMean$MeasuredWinrate)
ks.test(archetypeRankingDfAboveMean$MeasuredWinrate, "pnorm")
# Exponential presence
hist(archetypeRankingDfAboveMean$Matches,breaks = 15)
ks.test(archetypeRankingDfAboveMean$Matches, "pexp")
# Winrate and presence correlation
cor.test(archetypeRankingDfAboveMean$MeasuredWinrate, 
         archetypeRankingDfAboveMean$Matches/max(archetypeRankingDfAboveMean$Matches),
         method = "pearson")
regWRPres = lm(MeasuredWinrate ~ Matches, data = archetypeRankingDfAboveMean)
summary(regWRPres)
nrow(archetypeRankingDfAboveMean)
# Normal normalized sum
hist(archetypeRankingDfAboveMean$NormalizedSum)
shapiro.test(archetypeRankingDfAboveMean$NormalizedSum)
ks.test(archetypeRankingDfAboveMean$NormalizedSum, "pnorm")
normal_test(archetypeRankingDfAboveMean[archetypeRankingDfAboveMean$NormalizedSum>0,]$NormalizedSum)

# Murktide WR distribution
MurktideDf = tournamentDf[tournamentDf$Archetype$Archetype== "Murktide",]
nrow(MurktideDf)
hist(MurktideDf$Wins)
hist(MurktideDf$Wins/(MurktideDf$Wins+MurktideDf$Losses), breaks = 20)
plot(density(MurktideDf$Wins/(MurktideDf$Wins+MurktideDf$Losses)))
MurktideDfZeros = MurktideDf[MurktideDf$Wins==0,]
View(MurktideDfZeros[c("TournamentFile","Result","Wins","Losses","Draws")])
# install.packages("psych")              
library("psych")   
harmonic.mean(MurktideDf$Wins/(MurktideDf$Wins+MurktideDf$Losses))
