################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       _getter_Runner.R                               #####
##### Use this file to manually run some simple getters on the data        #####
################################################################################

# Set the working directory as the current R project directory 
# Mostly useful because the code keeps changing directories to write graphs
# Maybe it can do it otherwise and more efficiently?
library(rprojroot)
setwd(find_rstudio_root_file())

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = paste0(find_rstudio_root_file(),"/Scripts/")
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

functionScriptDir = paste0(importableScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

PathToLastDirs = 
  createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                          CsvResultDir, PictureResultDir, TextResultDir)

tournamentDf = 
  generate_df(EventType,MTGFormat,TournamentResultFile, Beginning, End)

################################################################################

cardName = "Wrenn and Six"
archetypeName = "Creativity"
archetypeName2 = "Murktide"

getConflictURL(tournamentDf)
getConflictArchetype(tournamentDf)
getUnknown(tournamentDf)
getURLofCard(cardName, tournamentDf)
getURLofDeck(archetypeName, tournamentDf)
getBestDeck(archetypeName, tournamentDf)
get_matchup_data(tournamentDf, archetypeName, archetypeName2)

# Get the required data to build the matchup matrix of a single archetype
muMatrixDataArchetype = generate_matchup_data(tournamentDf, ChartShare, 
                                              Presence, archetypeName)
# Draw the corresponding matchup matrix
# TODO : 
generate_matchup_matrix(muMatrixDataArchetype, ChartShare, Presence, Beginning, 
                        End, MtgFormat, EventType)

exportAchetypeCardData(archetypeName, tournamentDf)


