################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                              Main.R                                  #####
##### Use this file as a controller of the others to generate most results #####
################################################################################

# Set the working directory as the current R project directory 
# Mostly useful because the code keeps changing directories to write graphs
# Maybe it can do it otherwise and more efficiently?
library(rprojroot)
setwd(find_rstudio_root_file())

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = paste0(find_rstudio_root_file(),"/Scripts/")
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(ScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"01-Parameters.R")))

functionScriptDir = paste0(ScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"02-Tournament_Data_Import.R")))

tournamentDf=generate_df(EventType,MTGFormat,TournamentResultFile)

