################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                All_Constructed_Formats_Analysis.R                    #####
##### Generate an analysis for all the constructed formats                 #####
################################################################################

########################   Import data and functions   ######################### 

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = "Scripts/"
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

functionScriptDir = paste0(importableScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"02-Simple_Getters.R")))
source(file.path(paste0(functionScriptDir,"03-Metagame_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"04-Metagame_Graph_Generation.R")))
source(file.path(paste0(functionScriptDir,"05-Decklist_Analysis.R")))
source(file.path(paste0(functionScriptDir,"06-Player_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"07-Card_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

ConstructedFormats = MtgFormats[c(2:7)]

for(MtgFormat in ConstructedFormats){
  
  print(paste("FORMAT:",MtgFormat,"- Load data"))
  # Name of the tournament result data source file for the corresponding format
  # Currently automatically updated based on the format name
  TournamentResultFile = paste0(tournamentDataDir,MtgFormat,"_data.json")
  
  # Create all the directories where results will be written
  PathToLastDirs = 
    createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                            CsvResultDir, PictureResultDir, TextResultDir)
  
  # Import MTG JSON card data
  # mtgJsonFile = paste0(cardDataDir,MtgFormat,"Atomic.json")
  # mtgJsonData = bind_rows(jsonlite::fromJSON(mtgJsonFile)$data, .id = "cardName")
  
  #Import raw data
  RawData = jsonlite::fromJSON(TournamentResultFile)[[1]] 
  
  tournamentDf = generate_df(
    RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End)
  
  # Add a weight to the results depending on the number of weeks 
  # The most recent results become more important to determine the share and WR
  if(timeWeight){
    tournamentDf = addTimeWeight(tournamentDf)
    MtgFormat = paste(MtgFormat,"weighted by elapsed weeks")
  }
  
  ################################################################################
  ############################   Compute analysis   ############################## 
  ################################################################################
  
  print(paste("FORMAT:",MtgFormat,"- Compute analysis"))
  # Get the following columns: 
  # Archetype, Copies, Players, Matches, Measured.Win.Rate, Lower.Bound.of.CI.on.WR,
  # Upper.Bound.of.CI.on.WR, Normalized.Presence, Normalized.Win.Rate, 
  # Normalized.Sum.of.Presence.and.WR, Rank
  archetypeMetricsDf = archetype_metrics(tournamentDf, Presence)
  
  # Get the minimum presence to appear
  StatShare = updateStatShare(archetypeMetricsDf, ChartShare)
  
  # Keep only the most present decks and add the following columns:
  # Normalized.Presence, Normalized.Win.Rate, Normalized.Sum.of.Presence.and.WR, 
  archetypeNormalizedSumDf = 
    archetype_normalized_sum(archetypeMetricsDf, StatShare)
  
  # Add the following columns :
  # Rank.from.Normalized.Sum, Tiers.based.on.Normalized.Sum.of.Presence.and.WR, 
  # Rank.of.Lower.Bound.of.CI.on.WR, Tiers.based.on.Lower.Bound.of.CI.on.WR
  Tiers = c(names(archetypeNormalizedSumDf)[14], names(archetypeMetricsDf)[10])
  TierNames = paste0("Tiers.based.on.",Tiers)
  archetypeWithTiersDf = archetype_tiers(archetypeNormalizedSumDf, TierNames)
  
  # Get the required data to build the match up matrix of the most present
  # archetypes
  muMatrixData = generate_matchup_data(tournamentDf, ChartShare, Presence)
  
  ################################################################################
  ########################   Write the text synthesis   ########################## 
  ################################################################################
  
  print(paste("FORMAT:",MtgFormat,"- Write the text synthesis"))
  exportTextAnalysis(tournamentDf, PathToLastDirs, Beginning, End, MtgFormat, 
                     EventType, ChartShare,TextResultDir)
  
  ################################################################################
  #############################   Draw the plots   ############################### 
  ################################################################################
  
  print(paste("FORMAT:",MtgFormat,"- Draw the plots"))
  plotDir = paste0(PathToLastDirs,PictureResultDir)
  
  # Draw the metagame pie chart
  pieName = paste0(plotDir,"01_Presence-Pie-Chart_By-", Presence, "_", MtgFormat ,
                   "_", Beginning, "_", End, ".jpg")
  metagame_pie_chart(tournamentDf, ChartShare, Presence, Beginning, End, EventType,
                     MtgFormat)
  ggsave(pieName, width = 27, height = 20, units = "cm")
  # dev.off()
  
  # Draw the metagame bar chart
  barName = paste0(plotDir,"02_Presence-Bar-Chart_By-", Presence, "_", MtgFormat ,
                   "_", Beginning, "_", End, ".jpg")
  metagame_bar_chart(tournamentDf, StatShare, Presence, Beginning, End, EventType, 
                     MtgFormat)
  ggsave(barName, width = 30, height = 20, units = "cm")
  # dev.off()
  
  # Draw the win rate graph with confidence intervals
  winrateMustacheName = paste0(plotDir,"03_Winrate-Mustache-Box_", MtgFormat ,"_", 
                               Beginning, "_", End,".jpg")
  winrates_graph(archetypeMetricsDf, StatShare, Presence, Beginning, End,
                 EventType, MtgFormat, SortValue)
  ggsave(winrateMustacheName, width = 40, height = 20, units = "cm")
  # dev.off()
  
  # Draw the win rate graph with boxplots
  winrateBoxPlotName = paste0(plotDir,"04_Winrate-Box-Plot__", MtgFormat ,"_", 
                              Beginning, "_", End, ".jpg")
  boxplot_winrates(archetypeMetricsDf, tournamentDf, StatShare, Presence, 
                   Beginning, End,EventType, MtgFormat, SortValue)
  ggsave(winrateBoxPlotName, width = 40, height = 20, units = "cm")
  # dev.off()
  
  tierListName = 
    paste0(plotDir,"05_Scatterplot-of-",gsub("\\.", "-", TierNames[2]),
           "_", MtgFormat, "_", Beginning, "_", End, ".jpg")
  tier_list_graph(archetypeWithTiersDf, StatShare, Presence, Beginning, 
                  End, EventType, MtgFormat, Tiers[2])
  ggsave(tierListName, width = 80, height = 40, units = "cm")
  # dev.off()
  
  # Draw the 2D map of the archetypes based on presence and win rate
  winrateAndPresenceFullName = 
    paste0(plotDir,"06_Winrate-&-Presence-Full-Scatterplot_", MtgFormat,"_", 
           Beginning, "_", End,"_By-", Presence,".jpg")
  simple_winrate_and_presence_graph(archetypeMetricsDf, 0, Presence, 
                                    Diameters, Beginning, End, EventType, 
                                    MtgFormat, PresenceAxisLogScale)
  ggsave(winrateAndPresenceFullName, width = 60, height = 30, units = "cm")
  # dev.off()
  
  # Draw the 2D map of the most present archetypes based on presence and win rate,
  # adding the metrics as labels
  
  winrateAndPresenceFullName = 
    paste0(plotDir,"07_Winrate-&-Presence-Zoom-Scatterplot-with-",
           gsub("\\.", "-", TierNames[2]),"_", 
           MtgFormat,"_",Beginning, "_", End,".jpg")
  detailed_winrate_and_presence_graph(archetypeWithTiersDf, StatShare, Presence, 
                                      Beginning, End, EventType, MtgFormat, 
                                      PresenceAxisLogScale, TierNames[2])
  ggsave(winrateAndPresenceFullName, width = 60, height = 30, units = "cm")
  
  # Draw the corresponding matchup matrix
  matchupMatrixName = 
    paste0(plotDir,"08_Matchup-Matrix_", MtgFormat,"_", Beginning, "_", End,
           "_By-", Presence,".jpg")
  generate_matchup_matrix(muMatrixData, ChartShare, Presence, Beginning, End,
                          MtgFormat, EventType)
  ggsave(matchupMatrixName, width = 60, height = 30, units = "cm")
  # dev.off()
  
  ################################################################################
  #############################   Write the CSVs   ############################### 
  ################################################################################
  
  # print(paste("FORMAT:",MtgFormat,"- Write the CSVs"))
  # # Write the player results
  # exportPlayerData(tournamentDf,PathToLastDirs,Beginning,End,MtgFormat,EventType,
  #                  PlayerDataResultDir,writeCSV,writeXLSX,writeJSON)
  # 
  # # Write the card results
  # exportCardData(tournamentDf,PathToLastDirs,Beginning,End,MtgFormat,EventType,
  #                CardDataResultDir,writeCSV,writeXLSX,writeJSON)
  # 
  # # Write the archetype card results
  # archetypeCardData = lapply(archetypeWithTiersDf$Archetype, function(archetypeName){
  #   print(archetypeName)
  #   exportArchetypeCardData(archetypeName,tournamentDf,PathToLastDirs,Beginning,
  #                           End,MtgFormat,EventType,ArchetypeCardDataResultDir,
  #                           writeCSV,writeXLSX,writeJSON)
  #   
  #   exportArchetypeCardDataByCount(archetypeName,tournamentDf,PathToLastDirs,
  #                                  Beginning,End,MtgFormat,EventType,
  #                                  ArchetypeCardDataResultDir,writeCSV,
  #                                  writeXLSX,writeJSON)
  #   
  #   exportAverageDeckList(archetypeName,tournamentDf,PathToLastDirs,Beginning,
  #                         End,MtgFormat,EventType,AverageDeckListResultDir)
  #   
  #   exportAverageDeckList(archetypeName,tournamentDf,PathToLastDirs,Beginning,
  #                         End,MtgFormat,EventType,BestDeckResultDir)
  #   
  #   exportAllDeckURL(archetypeName,tournamentDf,PathToLastDirs,Beginning,
  #                    End,MtgFormat,EventType,AllDeckURLResultDir)
  #   
  #   # exportOptimizedDeckList(archetypeName,tournamentDf,PathToLastDirs,Beginning,
  #   #                       End,MtgFormat,EventType,OptimizedDeckListResultDir)
  # })
}


