################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                              Main.R                                  #####
##### Use this file as a controller of the others to generate most results #####
################################################################################

########################   Import data and functions   ######################### 

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = "Scripts/"
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

functionScriptDir = paste0(importableScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"02-Simple_Getters.R")))
source(file.path(paste0(functionScriptDir,"03-Metagame_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"04-Metagame_Graph_Generation.R")))
source(file.path(paste0(functionScriptDir,"05-Decklist_Analysis.R")))
source(file.path(paste0(functionScriptDir,"06-Player_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"07-Card_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

# Create all the directories where results will be written
PathToLastDirs = 
  createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                          CsvResultDir, PictureResultDir, TextResultDir)

# # Import MTG JSON card data
# mtgJsonData = bind_rows(jsonlite::fromJSON(mtgJsonFile)$data, .id = "cardName")

#Import tournament raw data
RawData = jsonlite::fromJSON(TournamentResultFile)[[1]] 
Beginning = min(RawData$Date)
End = max(RawData$Date)
EventType = EventTypes[2]
MtgFormat = MtgFormats[4]

tournamentDf = generate_df(
  RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End)

# Création d'un nouveau dataframe, en excluant le premier métagame et en calculant les fréquences

new_df <- tournamentDf %>%
  filter(Meta != "StartOfMtgoData") %>%
  group_by(Meta) %>%
  mutate(total = n()) %>%
  group_by(Meta, Archetype$Archetype) %>%
  summarise(Frequency = 100 * n() / first(total)) %>%
  # Ici, on arrange les données par l'ordre d'apparition des métagames dans tournamentDf
  arrange(match(Meta, unique(tournamentDf$Meta))) %>%
  pivot_wider(names_from = Meta, values_from = Frequency, values_fill = 0)

# Affichage du nouveau dataframe
# View(new_df)

# Supposons que tournamentDf contient les colonnes "Date", "Wins", "Losses", "Draws" et "Meta"
# et que new_df_summary est le dataframe créé précédemment

# Calculer les dates de début et de fin de chaque métagame
date_ranges <- tournamentDf %>%
  group_by(Meta) %>%
  summarize(
    Start_Date = min(Date),
    End_Date = max(Date)
  )

# Calculer la durée en jours
date_ranges <- date_ranges %>%
  mutate(Duree = as.numeric(End_Date - Start_Date) + 1)  # Ajouter 1 pour inclure le dernier jour

# Joindre les résultats à new_df_summary
new_df_summary <- new_df %>%
  pivot_longer(cols = -`Archetype$Archetype`, names_to = "Meta", values_to = "Frequency") %>%
  group_by(Meta) %>%
  summarize(
    Nb_Archetypes = sum(Frequency > 0),
    Freq_Archetype_Max = max(Frequency),
    Sum_Freq_Top5 = sum(sort(Frequency, decreasing = TRUE)[1:5]),
    Sum_Freq_Top10 = sum(sort(Frequency, decreasing = TRUE)[1:10])
  ) %>%
  arrange(match(Meta, unique(tournamentDf$Meta))) %>%
  left_join(date_ranges, by = "Meta")

# Affichage du tableau
print(new_df_summary)

write.table(new_df_summary, "Results/metagame_comparison_results.csv", 
           row.names = FALSE, sep = ";")

library(tidyverse)

# Supposons que new_df ait la structure suivante :
# | Archetype | Metagame1 | Metagame2 | ... |
# |---|---|---|---|

# Transformer new_df en format long
new_df_long <- new_df %>%
  pivot_longer(cols = -`Archetype$Archetype`, names_to = "Metagame", values_to = "Count")

# Calculer l'IHH pour chaque métagame
IHH_by_metagame_descending <- new_df_long %>%
  group_by(Metagame) %>%
  summarize(
    Total_count = sum(Count),
    IHH = sum((Count / Total_count)^2)
  ) %>%
  arrange(desc(IHH))
IHH_by_metagame_descending

# Trier par ordre décroissant de IHH1984
IHH_by_metagame_ascending <- IHH_by_metagame_descending %>%
  arrange(IHH)
IHH_by_metagame_ascending
