################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       _getter_Runner.R                               #####
##### Use this file to manually run some simple getters on the data        #####
################################################################################

########################   Import data and functions   ######################### 

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = "Scripts/"
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

functionScriptDir = paste0(importableScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"02-Simple_Getters.R")))
source(file.path(paste0(functionScriptDir,"03-Metagame_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"04-Metagame_Graph_Generation.R")))
source(file.path(paste0(functionScriptDir,"05-Decklist_Analysis.R")))
source(file.path(paste0(functionScriptDir,"06-Player_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"07-Card_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

PathToLastDirs = 
  createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                          CsvResultDir, PictureResultDir, TextResultDir)

#Import raw data
RawData = jsonlite::fromJSON(TournamentResultFile)[[1]]
tournamentDf = generate_df(
  RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End)

############################   Compute analysis   ############################## 

OmnathPileDf = tournamentDf[tournamentDf$Archetype$Archetype == "Omnath Control",]

OmnathPileDf$SubArchetype = paste(OmnathPileDf$Archetype$Companion, 
                                        OmnathPileDf$Archetype$Archetype)

OmnathPileDf$SubArchetype = 
  ifelse(sapply(OmnathPileDf$Mainboard, 
              function(boards){"Delighted Halfling" %in% boards$CardName}),
         "Halfling Omnath Control", OmnathPileDf$SubArchetype)

OmnathPileDf[OmnathPileDf$SubArchetype == " Omnath Control",]$SubArchetype = "Other Omnath Control"

OmnathPileDf$Archetype$Archetype = OmnathPileDf$SubArchetype

table(OmnathPileDf$Archetype$Archetype)

# Write the archetype card results
archetypeCardData = lapply(unique(OmnathPileDf$SubArchetype), function(archetypeName){
  print(archetypeName)
  exportArchetypeCardData(archetypeName,OmnathPileDf,PathToLastDirs,Beginning,
                          End,MtgFormat,EventType,ArchetypeCardDataResultDir,
                          writeCSV,writeXLSX,writeJSON)
  
  exportArchetypeCardDataByCount(archetypeName,OmnathPileDf,PathToLastDirs,
                                 Beginning,End,MtgFormat,EventType,
                                 ArchetypeCardDataResultDir,writeCSV,writeXLSX,
                                 writeJSON)
  
  exportAverageDeckList(archetypeName,OmnathPileDf,PathToLastDirs,Beginning,
                        End,MtgFormat,EventType,AverageDeckListResultDir)
  
  exportBestDeck(archetypeName,OmnathPileDf,PathToLastDirs,Beginning,
                 End,MtgFormat,EventType,BestDeckResultDir)
  
  exportAllDeckURL(archetypeName,OmnathPileDf,PathToLastDirs,Beginning,
                   End,MtgFormat,EventType,AllDeckURLResultDir)
  
  exportOptimizedDeckList(archetypeName,OmnathPileDf,PathToLastDirs,Beginning,
                        End,MtgFormat,EventType,OptimizedDeckListResultDir)
})
