################################################################################
#####                  MTG Tournament Result Analysis                      #####
#####                           by Anaël Yahi                              #####
#####               based on data generated by Phelps-san                  #####
#####            https://github.com/Badaro/MTGOArchetypeParser             #####
################################################################################
#####                       week_comparison.R                              #####
##### Use this file as a controller of the others to generate most results #####
################################################################################

########################   Import data and functions   ######################### 

# Import the parameters, libraries and functions from other scripts
# Once the code is stable, it should be turned into packages
ScriptDir = "Scripts/"
importableScriptDir = paste0(ScriptDir,"Imports/")

parameterScriptDir = paste0(importableScriptDir,"Parameters/")
source(file.path(paste0(parameterScriptDir,"Parameters.R")))

functionScriptDir = paste0(importableScriptDir,"Functions/")
source(file.path(paste0(functionScriptDir,"01-Tournament_Data_Import.R")))
source(file.path(paste0(functionScriptDir,"02-Metagame_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"03-Metagame_Graph_Generation.R")))
source(file.path(paste0(functionScriptDir,"04-Decklist_Analysis.R")))
source(file.path(paste0(functionScriptDir,"05-Player_Data_Treatment.R")))
source(file.path(paste0(functionScriptDir,"99-Output_Export.R")))

# Create all the directories where results will be written
PathToLastDirs = 
  createResultDirectories(ResultDir, MtgFormat, Beginning, End, EventType,
                          CsvResultDir, PictureResultDir, TextResultDir)

#Import raw data
RawData = fromJSON(TournamentResultFile)[[1]] 

# Generate data for the whole month
tournamentDf = generate_df(
  RawData, EventType, MtgFormat, TournamentResultFile, Beginning, End)
archetypeMetricsDf = archetype_metrics(tournamentDf)
StatShare = 
  round(mean(unlist(archetypeMetricsDf[Presence])) / 
          sum(unlist(archetypeMetricsDf[Presence])) * 100, digits = 2)
metagameDf = generate_metagame_data(tournamentDf, StatShare, Presence)

# Split data by week
beginnings = seq(as.Date(Beginning), as.Date(Beginning) + 27, "7 days")
ends = seq(as.Date(Beginning) + 7, as.Date(Beginning) + 28, "7 days")
BeginningAndEnd = data.frame(beginnings = beginnings,ends = ends)
weekCount = 1:nrow(BeginningAndEnd)

weeklyResults = lapply(weekCount, function(weekIndex,RawData, EventType, MtgFormat, TournamentResultFile){
  beginning = BeginningAndEnd$beginnings[weekIndex]
  end = BeginningAndEnd$ends[weekIndex]
  print(paste("Beginning:",beginning, " - End:",end))
  tournamentDf = generate_df(
    RawData, EventType, MtgFormat, TournamentResultFile, beginning, end)
},RawData, EventType, MtgFormat, TournamentResultFile)

weeklyMetrics = lapply(weeklyResults, archetype_metrics)
weeklyMetrics = lapply(weeklyMetrics, function(weeklyMetric){
  weeklyMetric$Share = 
    round(weeklyMetric$Copies / sum(weeklyMetric$Copies)*100, digits = 2)
  weeklyMetric
})

# Combine weekly data in a single data frame
weeklyMetric1 = weeklyMetrics[[1]]
metagameDf$Week1Share = sapply(metagameDf$Archetype, function(archetype){
  weeklyMetric1[weeklyMetric1$Archetype == archetype,]$Share
})

weeklyMetric2 = weeklyMetrics[[2]]
metagameDf$Week2Share = sapply(metagameDf$Archetype, function(archetype){
  weeklyMetric2[weeklyMetric2$Archetype == archetype,]$Share
})

weeklyMetric3 = weeklyMetrics[[3]]
metagameDf$Week3Share = sapply(metagameDf$Archetype, function(archetype){
  weeklyMetric3[weeklyMetric3$Archetype == archetype,]$Share
})

weeklyMetric4 = weeklyMetrics[[4]]
metagameDf$Week4Share = sapply(metagameDf$Archetype, function(archetype){
  weeklyMetric4[weeklyMetric4$Archetype == archetype,]$Share
})

# Remove "Others"
metagameDf = metagameDf[!grepl("Other",metagameDf$Archetype),]
metagameDf

# Load the ggplot2 and tidyr packages for plotting and reshaping
library(ggplot2)
library(tidyr)

# Keep less archetypes for plotting, only top10
metagameDfSmall = metagameDf[1:10, ]

# Convert the Archetype variable from factor to character
metagameDfSmall$Archetype = as.character(metagameDfSmall$Archetype)

# Convert the Week1Share, Week2Share, Week3Share, and Week4Share variables from lists to numerics
metagameDfSmall$Week1Share = 
  unlist(metagameDfSmall$Week1Share)
metagameDfSmall$Week2Share = 
  unlist(metagameDfSmall$Week2Share)
metagameDfSmall$Week3Share = 
  unlist(metagameDfSmall$Week3Share)
metagameDfSmall$Week4Share = 
  unlist(metagameDfSmall$Week4Share)

# Rename the Share variable to TotalShare
metagameDfSmall = 
  rename(metagameDfSmall, TotalShare = Share)

# Load the ggplot2 and tidyr packages for plotting and reshaping
library(ggplot2)
library(tidyr)

# Reshape the dataframe to have a long format using the tidyr package
metagameDfPivoted =
  pivot_longer(metagameDfSmall, cols = starts_with("Week"), 
               names_to = "Week", values_to = "Share")

# Plot the evolution of the share week after week of the archetypes
ggplot(metagameDfPivoted, aes(x = Week, y = Share, group = Archetype, color = Archetype)) +
  geom_line(size = 1.5) +
  geom_point(size = 3) +
  scale_x_discrete(labels = beginnings,
                   limits = c("Week1Share", "Week2Share", "Week3Share", "Week4Share")) +
  labs(title = paste("Evolution of the share week after week of the most present", 
  MtgFormat,"archetypes\nbetween", beginnings[1],"and",ends[1]),
       subtitle = "by Anaël Yahi",
       x = "Week",
       y = "Share (%)",
       color = "Archetype") +
  theme_minimal()
# Save the metagame weekly evolution chart
plotDir = paste0(PathToLastDirs,PictureResultDir)
weeklyEvolutionName = paste0(plotDir,"09_Weekly_Evolution_Chart_", MtgFormat ,"_", Beginning, 
                 "_", End,"_By-", Presence, ".jpg")
ggsave(weeklyEvolutionName, width = 27, height = 20, units = "cm")
dev.off()

# Save tables of the full archetype evolution data
archetypeWeeklyShareDirPath = paste0(PathToLastDirs, ArchetypeWeeklyShareResultDir)
archetypeWeeklyShareFileName = paste0(Beginning,"_", End, " - Archetype Share over weeks in ", 
                                      MtgFormat, " based on ", EventType)
dir.create(file.path(archetypeWeeklyShareDirPath))
write.csv(metagameDf,
          paste0(archetypeWeeklyShareDirPath, archetypeWeeklyShareFileName,'.csv'), 
          row.names = FALSE)
write.xlsx(metagameDf,
           paste0(archetypeWeeklyShareDirPath, archetypeWeeklyShareFileName,'.xlsx'), 
           row.names = FALSE)



